"""
Authored from "6 Advanced JavaScript Questions That Separate Seniors from
Mid-Levels" (DEV Community).

These are output-prediction questions whose options are literal console
transcripts, so they render in the Homebrew terminal skin.
"""

SOURCE = "advanced-javascript-6"
LEVEL = "senior"
CATEGORY = "javascript"
LANG = "javascript"

QUESTIONS = [
    {
        "id": "javascript-stale-closure-primitive-capture",
        "title": "Closures capture variables, not the expressions that filled them",
        "prompt": "What does log() print after increment() has run twice?",
        "type": "output",
        "subject": "closures",
        "tags": ["javascript", "closures", "lexical-scope", "senior"],
        "codeSnippet": "function createIncrement() {\n  let count = 0;\n  const message = `Count is ${count}`;\n\n  function increment() {\n    count++;\n  }\n\n  function log() {\n    console.log(message);\n  }\n\n  return { increment, log };\n}\n\nconst { increment, log } = createIncrement();\nincrement();\nincrement();\nlog();",
        "options": [
            ("A", "Count is 0", True,
             "Correct. The template literal was evaluated once, at assignment. message holds the finished string and never re-runs."),
            ("B", "Count is 2", False,
             "That would require message to be re-evaluated when log() runs. A const string is computed once."),
            ("C", "Count is 1", False,
             "count did reach 2, but message never re-reads it at all."),
            ("D", "undefined", False,
             "message is assigned before either inner function is ever called, so it is a real string."),
        ],
        "explanation": "Both inner functions close over the same lexical environment, so they genuinely share count — increment() really does take it from 0 to 2. But message is a const string whose template literal was evaluated once, at the moment of assignment, when count was still 0. Closing over a variable does not make the expression that produced its value re-run. To see the current count, log would have to read count itself and build the string at call time.",
        "interviewLine": "Closures capture variables, not expressions. If the variable holds a primitive computed once, you're looking at a snapshot forever.",
        "misconception": "Believing a closure re-evaluates the expression it closed over. It closes over the binding, and that binding already holds a finished value.",
        "hints": ["When exactly does the template literal run — at assignment or at call?"],
        "minutes": 3,
    },
    {
        "id": "javascript-this-binding-three-ways",
        "title": "Three call sites, three different values of this",
        "prompt": "What does user.greet() log?",
        "type": "output",
        "subject": "closures",
        "tags": ["javascript", "this", "arrow-functions", "binding", "senior"],
        "codeSnippet": "const user = {\n  name: \"Alex\",\n  greet() {\n    console.log(`Hello, ${this.name}!`);\n\n    const innerNormal = function () {\n      console.log(`Normal: ${this.name}`);\n    };\n    const innerArrow = () => {\n      console.log(`Arrow: ${this.name}`);\n    };\n\n    innerNormal();\n    innerArrow();\n  },\n};\n\nuser.greet();",
        "options": [
            ("A", "Hello, Alex!\nNormal: Alex\nArrow: Alex", False,
             "innerNormal is called with no receiver, so it does not inherit greet's this."),
            ("B", "Hello, Alex!\nNormal: undefined\nArrow: Alex", True,
             "Correct. Method call binds this to user; a bare function call has no receiver; the arrow captures greet's this lexically."),
            ("C", "Hello, Alex!\nNormal: undefined\nArrow: undefined", False,
             "The arrow function has no this of its own — it uses greet's, which is user."),
            ("D", "Hello, undefined!\nNormal: undefined\nArrow: undefined", False,
             "greet is invoked as user.greet(), so its this is user."),
        ],
        "explanation": "Regular functions resolve this at call time from how they were called. user.greet() has a receiver, so this is user. innerNormal() is called bare — no receiver — so this is undefined in strict mode (modules are always strict), and reading .name off it throws or yields undefined depending on the surrounding mode. Arrow functions have no this binding at all; innerArrow closes over greet's this lexically, so it still sees user.",
        "interviewLine": "Regular functions bind this at call time; arrows capture it at definition time. Losing a receiver loses the binding.",
        "misconception": "Expecting a nested regular function to inherit the enclosing method's this. It does not — only arrows do.",
        "hints": ["Look at how each function is *called*, not where it is written."],
        "minutes": 3,
    },
    {
        "id": "javascript-prototype-read-vs-write",
        "title": "Why += creates an own property but .push() does not",
        "prompt": "What do the four logs print?",
        "type": "output",
        "subject": "design-patterns",
        "tags": ["javascript", "prototypes", "mutation", "object-create", "senior"],
        "codeSnippet": "const grandparent = { heritage: [\"gold\", \"land\"], coins: 100 };\nconst parent = Object.create(grandparent);\nconst child = Object.create(parent);\n\nchild.coins += 50;\nchild.heritage.push(\"debts\");\n\nconsole.log(grandparent.coins);\nconsole.log(grandparent.heritage);\nconsole.log(child.coins);\nconsole.log(child.heritage);",
        "options": [
            ("A", "150\n[\"gold\", \"land\", \"debts\"]\n150\n[\"gold\", \"land\", \"debts\"]", False,
             "grandparent.coins is never written to — the assignment lands on child."),
            ("B", "100\n[\"gold\", \"land\"]\n150\n[\"gold\", \"land\", \"debts\"]", False,
             "child.heritage is not a copy; it is the same array object, so the push is visible from grandparent too."),
            ("C", "100\n[\"gold\", \"land\", \"debts\"]\n150\n[\"gold\", \"land\", \"debts\"]", True,
             "Correct. The write to coins creates an own property on child; the push mutates the single shared array reached through the prototype chain."),
            ("D", "100\n[\"gold\", \"land\"]\n100\n[\"gold\", \"land\"]", False,
             "child.coins += 50 does write 150 onto child."),
        ],
        "explanation": "Reads walk the prototype chain; writes always land on the object that received the assignment. child.coins += 50 reads 100 from grandparent, adds 50, then writes 150 as a new own property on child — grandparent keeps 100. child.heritage.push('debts') never assigns to heritage at all: it reads the array reference from grandparent and mutates that one shared array, so every object in the chain sees the new element. To get an independent array you must assign a copy: child.heritage = [...child.heritage, 'debts'].",
        "interviewLine": "Reads go up the prototype chain; writes stop at the object you wrote to. Mutating a value you read is not a write.",
        "misconception": "Assuming reading a property through the prototype chain gives you your own copy of it. You get the same reference.",
        "hints": ["Which of these two lines actually performs an assignment?"],
        "minutes": 3,
    },
    {
        "id": "javascript-coercion-precedence-trap",
        "title": "Unary operators, array coercion and left-to-right +",
        "prompt": "What does this log?",
        "type": "output",
        "subject": "types",
        "tags": ["javascript", "coercion", "operators", "precedence", "senior"],
        "codeSnippet": "console.log(+\"5\" + [1] + !\"0\");",
        "options": [
            ("A", "\"51false\"", True,
             "Correct. Unary operators run first, then binary + evaluates left to right, coercing to string as soon as one side is a string."),
            ("B", "6", False,
             "Only the first operand becomes a number. [1] coerces to the string \"1\", which turns the whole expression into string concatenation."),
            ("C", "\"5,1false\"", False,
             "A single-element array stringifies to \"1\" with no comma; commas only appear for multiple elements."),
            ("D", "NaN", False,
             "No arithmetic on a non-numeric value happens — the expression becomes string concatenation before that could occur."),
        ],
        "explanation": "Unary operators bind tighter than binary +, so +\"5\" becomes the number 5 and !\"0\" becomes false — \"0\" is a non-empty string and therefore truthy. That leaves 5 + [1] + false. Binary + is left-associative: 5 + [1] converts the array to a primitive, which for [1] is the string \"1\", so string concatenation wins and gives \"51\". Then \"51\" + false gives \"51false\".",
        "interviewLine": "Binary + is the only arithmetic operator that also concatenates — one string operand anywhere and the whole chain turns into text.",
        "misconception": "Thinking !\"0\" is true. The string \"0\" is truthy; only the empty string is falsy.",
        "hints": ["Evaluate the two unary operators first, then go left to right."],
        "minutes": 2,
    },
    {
        "id": "javascript-event-loop-macrotask-microtask-order",
        "title": "Ordering the call stack, microtasks and macrotasks",
        "prompt": "In what order do the numbers print?",
        "type": "output",
        "subject": "event-loop",
        "tags": ["javascript", "event-loop", "microtasks", "settimeout", "senior"],
        "codeSnippet": "console.log(\"1\");\n\nsetTimeout(() => {\n  console.log(\"2\");\n  Promise.resolve().then(() => console.log(\"3\"));\n}, 0);\n\nnew Promise((resolve) => {\n  console.log(\"4\");\n  resolve();\n}).then(() => {\n  console.log(\"5\");\n  setTimeout(() => console.log(\"6\"), 0);\n});\n\nconsole.log(\"7\");",
        "options": [
            ("A", "1 4 7 5 2 3 6", True,
             "Correct. Synchronous code first, then the microtask queue drains completely, then macrotasks in the order they were scheduled."),
            ("B", "1 4 7 2 3 5 6", False,
             "The .then callback is a microtask and runs before any setTimeout, which is a macrotask."),
            ("C", "1 2 3 4 5 6 7", False,
             "Nothing asynchronous can run before the synchronous script finishes."),
            ("D", "1 4 5 7 2 3 6", False,
             "console.log(\"7\") is synchronous, so it runs before any microtask."),
        ],
        "explanation": "The synchronous pass prints 1, then 4 (the Promise executor runs immediately), then 7. Only when the stack empties does the microtask queue drain: the .then prints 5 and schedules another setTimeout. Then macrotasks run in scheduling order — the first timer prints 2 and queues a microtask, which drains before the next macrotask, giving 3. Finally the timer scheduled from inside the microtask prints 6.",
        "interviewLine": "The whole microtask queue drains between every pair of macrotasks — not one microtask, all of them.",
        "misconception": "Treating setTimeout(fn, 0) as 'run next'. It is a macrotask and always yields to every pending microtask.",
        "hints": ["A Promise executor body is synchronous; only .then callbacks are deferred."],
        "minutes": 3,
    },
    {
        "id": "javascript-await-vs-then-scheduling",
        "title": "Where await resumes relative to a .then chain",
        "prompt": "In what order do the logs appear?",
        "type": "output",
        "subject": "async-await",
        "tags": ["javascript", "async-await", "microtasks", "promises", "senior"],
        "codeSnippet": "async function asyncFunc() {\n  console.log(\"2\");\n  await Promise.resolve();\n  console.log(\"3\");\n}\n\nconsole.log(\"1\");\nasyncFunc();\n\nPromise.resolve()\n  .then(() => console.log(\"4\"))\n  .then(() => console.log(\"5\"));\n\nconsole.log(\"6\");",
        "options": [
            ("A", "1 2 6 4 3 5", False,
             "The await continuation was queued before the first .then callback, so 3 comes first."),
            ("B", "1 2 6 3 4 5", True,
             "Correct. An async function body runs synchronously up to the first await; the continuation is queued as a microtask ahead of the later .then."),
            ("C", "1 2 3 6 4 5", False,
             "Code after await never runs synchronously — it always resumes in a microtask."),
            ("D", "1 6 2 3 4 5", False,
             "Calling an async function runs its body immediately until the first await, so 2 prints before 6."),
        ],
        "explanation": "Calling asyncFunc() runs its body synchronously until the first await, so 1 and 2 print in order. The await on an already-resolved promise queues the continuation as a microtask — and it is queued before the .then chain is registered on the following line. Then 6 prints, ending the synchronous pass. The microtask queue drains in order: 3 (the await continuation), then 4, and only once that handler returns is the second .then queued, giving 5.",
        "interviewLine": "await is a microtask boundary — the body runs synchronously up to it, and everything after resumes in queue order.",
        "misconception": "Assuming a .then registered earlier in the source always runs before an await continuation. What matters is the order the callbacks were queued.",
        "hints": ["Which continuation reaches the microtask queue first?"],
        "minutes": 3,
    },
]
