"""
Authored from "25+ TypeScript Interview Questions For Tech Interviews"
(CoderPad), which groups its material by junior / intermediate / senior.

The source repeats several concept questions verbatim across all three levels;
only one copy of each is kept here. Its debugging questions are kept as `fix`
items, which is where the bank is thinnest.

One correction: the source claims spreading a value typed `object` is an error
(its junior mergeObjects item) while its senior item says the same code is
fine. The senior item is right — spreading `object` is legal — so that question
is authored around the real weakness, which is the widened return type.
"""

SOURCE = "coderpad-typescript"
CATEGORY = "typescript"
LANG = "typescript"

QUESTIONS = [
    # ---------------------------------------------------------------- concepts
    {
        "id": "typescript-superset-static-typing-basics",
        "title": "What TypeScript adds on top of JavaScript",
        "prompt": "Which statement best describes TypeScript's relationship to JavaScript?",
        "level": "junior", "type": "concept", "subject": "types",
        "tags": ["typescript", "fundamentals", "tooling"],
        "codeSnippet": "function add(a: number, b: number): number {\n  return a + b;\n}",
        "options": [
            ("A", "A superset that adds optional static types, all of which are erased before the code runs", True,
             "Correct. Every valid JavaScript file is valid TypeScript, and the types exist only at compile time."),
            ("B", "A separate language that compiles to JavaScript but shares no syntax with it", False,
             "It is a strict superset — plain JavaScript is already valid TypeScript."),
            ("C", "A runtime that enforces types while the program executes", False,
             "There is no runtime type checking. Annotations are stripped by the compiler."),
            ("D", "A linter that reports type problems without changing the output", False,
             "It is a compiler with its own syntax — enums, interfaces, generics — not a linting layer over JavaScript."),
        ],
        "explanation": "TypeScript is a superset: valid JavaScript is already valid TypeScript, and you opt into typing gradually. Everything the type system knows is discarded by the compiler, so the emitted JavaScript has no annotations and no runtime cost — and equally no runtime protection. A value that arrives from an API as the wrong shape will not be caught unless you validate it yourself.",
        "interviewLine": "Types are compile-time only. They're erased before the code runs, so they catch your mistakes, not your users' data.",
        "misconception": "Expecting TypeScript to validate data at runtime. A type assertion on an API response checks nothing.",
        "hints": ["What is left in the emitted JavaScript after compilation?"],
        "minutes": 2,
    },
    {
        "id": "typescript-interfaces-describe-shape",
        "title": "What an interface is for",
        "prompt": "What does an interface do in TypeScript?",
        "level": "junior", "type": "concept", "subject": "types",
        "tags": ["typescript", "interfaces", "contracts"],
        "codeSnippet": "interface Person {\n  firstName: string;\n  lastName: string;\n  greet(): void;\n}\n\nclass Employee implements Person {\n  constructor(\n    public firstName: string,\n    public lastName: string,\n  ) {}\n  greet() {\n    console.log(`Hi, ${this.firstName}`);\n  }\n}",
        "options": [
            ("A", "It generates a runtime class with default implementations", False,
             "Interfaces emit nothing at all. There is no runtime artifact."),
            ("B", "It describes the shape a value must have, and is erased at compile time", True,
             "Correct. It is a compile-time contract — properties, their types, and method signatures."),
            ("C", "It creates a new value that can be instantiated with new", False,
             "You cannot instantiate an interface; only classes produce values."),
            ("D", "It validates objects against the declared shape when they are created", False,
             "No validation happens at runtime. Checking is entirely static."),
        ],
        "explanation": "An interface declares the shape a value must have — which properties exist, what types they hold, what methods they expose — and emits nothing. A class can declare implements Person to have the compiler verify it satisfies the contract, but any object with the right shape also satisfies it, because TypeScript is structurally typed rather than nominally typed. Interfaces also merge across declarations, which is what makes them the right choice for shapes other code may extend.",
        "interviewLine": "An interface is a compile-time contract, not a runtime object. Structural typing means anything with the right shape satisfies it.",
        "misconception": "Thinking a value must explicitly implement an interface to be assignable to it. Structural typing says otherwise.",
        "hints": ["What does an interface compile down to?"],
        "minutes": 2,
    },
    {
        "id": "typescript-generics-preserve-type-relationship",
        "title": "What a generic buys you over any",
        "prompt": "Why is identity<T>(value: T): T better than identity(value: any): any?",
        "level": "junior", "type": "concept", "subject": "generics",
        "tags": ["typescript", "generics", "any", "type-safety"],
        "codeSnippet": "function identity<T>(value: T): T {\n  return value;\n}\n\nconst n = identity(42);      // number\nconst s = identity(\"hello\"); // string",
        "options": [
            ("A", "The generic preserves the relationship between argument and return type; any discards it", True,
             "Correct. T links input to output, so the caller keeps the concrete type instead of falling back to any."),
            ("B", "The generic version runs faster because it avoids runtime type checks", False,
             "Neither performs runtime checks; both compile to the same JavaScript."),
            ("C", "any is not allowed as a return type in strict mode", False,
             "any is permitted everywhere. strict does not forbid it."),
            ("D", "The generic restricts the function to a single type across the whole program", False,
             "T is resolved per call site, so different calls can use different types."),
        ],
        "explanation": "any switches off the type system: identity(42) returns any, and from there you can call .toUpperCase() on a number with no complaint. A type parameter instead captures whatever the caller passed and threads it through to the return type, so identity(42) is number and identity('hello') is string. Generics keep information flowing; any throws it away.",
        "interviewLine": "A generic relates types to each other; any just gives up. Reach for a type parameter whenever output depends on input.",
        "misconception": "Treating any as a lightweight generic. It is the absence of typing, not a flexible form of it.",
        "hints": ["What type does the caller get back in each version?"],
        "minutes": 2,
    },
    {
        "id": "typescript-decorators-what-they-modify",
        "title": "What a decorator can attach to",
        "prompt": "What is a decorator in TypeScript?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "decorators", "metadata"],
        "codeSnippet": "function log(target: unknown, key: string, descriptor: PropertyDescriptor) {\n  const original = descriptor.value;\n  descriptor.value = function (...args: unknown[]) {\n    console.log(`calling ${key}`);\n    return original.apply(this, args);\n  };\n}\n\nclass Service {\n  @log\n  fetch() {}\n}",
        "options": [
            ("A", "A type-level annotation that the compiler erases like any other type", False,
             "Decorators emit real runtime code — they are not erased."),
            ("B", "A function that wraps or annotates a class, method, accessor, property or parameter at definition time", True,
             "Correct. It runs when the definition is evaluated and can replace or annotate what it decorates."),
            ("C", "A macro expanded inline at each call site", False,
             "It runs once at definition, not at each call, and it is an ordinary function rather than a macro."),
            ("D", "A shorthand for declaration merging on classes", False,
             "Decorators and declaration merging are unrelated features."),
        ],
        "explanation": "A decorator is a function applied to a declaration when that declaration is evaluated. It receives the target and can wrap, replace or annotate it — the classic example replaces a method's implementation with one that logs and delegates. Unlike types, decorators emit real runtime code. Angular and NestJS are built on them, and after years as an experimental flag they are now a standardised JavaScript feature.",
        "interviewLine": "Decorators run at definition time and emit real code — unlike everything else in TypeScript's syntax, they are not erased.",
        "misconception": "Assuming decorators are compile-time only like type annotations. They produce runtime behaviour.",
        "hints": ["Is there anything left in the emitted JavaScript?"],
        "minutes": 3,
    },
    {
        "id": "typescript-async-await-over-promises",
        "title": "What async/await changes about a promise",
        "prompt": "How does async/await relate to promises?",
        "level": "junior", "type": "concept", "subject": "async-await",
        "tags": ["typescript", "async-await", "promises"],
        "codeSnippet": "async function loadUser(id: string): Promise<User> {\n  const res = await fetch(`/api/users/${id}`);\n  if (!res.ok) throw new Error(res.statusText);\n  return res.json();\n}",
        "options": [
            ("A", "It replaces promises with a different concurrency primitive", False,
             "It is built directly on promises — an async function returns one."),
            ("B", "It makes asynchronous calls run synchronously, blocking the thread", False,
             "Nothing blocks. await yields control and resumes later in a microtask."),
            ("C", "It is syntax over promises: an async function returns one, and await unwraps one", True,
             "Correct. Same machinery, and it lets try/catch handle rejections."),
            ("D", "It only works with promises created by fetch", False,
             "await works on any thenable, whatever produced it."),
        ],
        "explanation": "An async function always returns a promise, and await suspends the function until the awaited promise settles — yielding to the event loop rather than blocking. The practical win is control flow: sequential code reads top to bottom instead of nesting in .then chains, and ordinary try/catch handles rejection. The cost is that awaiting in sequence serialises work that could have run concurrently, which is what Promise.all is for.",
        "interviewLine": "await doesn't block, it yields. Sequential awaits serialise independent work — reach for Promise.all when the calls don't depend on each other.",
        "misconception": "Assuming await blocks the thread. It suspends one function while everything else keeps running.",
        "hints": ["What does an async function return, always?"],
        "minutes": 2,
    },
    {
        "id": "typescript-modules-encapsulation",
        "title": "What makes a file a module",
        "prompt": "In TypeScript, what determines whether a file is a module rather than a global script?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "modules", "scope"],
        "codeSnippet": "// utils.ts — a module: it has an export\nexport function toSlug(s: string) {\n  return s.toLowerCase().replace(/\\s+/g, \"-\");\n}\n\n// globals.ts — a script: no import or export anywhere\nconst VERSION = \"1.0\";",
        "options": [
            ("A", "The .ts extension — every TypeScript file is a module", False,
             "A .ts file with no import or export is a global script."),
            ("B", "The presence of at least one top-level import or export", True,
             "Correct. That is the rule; without one, declarations land in the global scope and can collide."),
            ("C", "Being listed in the include array of tsconfig.json", False,
             "That controls which files are compiled, not whether they are modules."),
            ("D", "Setting module in tsconfig.json", False,
             "That selects the output module format for files that are already modules."),
        ],
        "explanation": "A file becomes a module the moment it has a top-level import or export. Until then its declarations live in the global scope, which is how two files can collide on the same const name. That is also why an otherwise empty declaration file sometimes needs export {} to force module status. --isolatedModules makes this explicit by requiring every file to be a module.",
        "interviewLine": "One top-level import or export is the whole rule. Without it you're writing globals, whether you meant to or not.",
        "misconception": "Assuming every .ts file is automatically scoped. Without an import or export it shares the global scope.",
        "hints": ["Why would you ever write a bare `export {}` in a file?"],
        "minutes": 2,
    },

    # -------------------------------------------------------------------- fixes
    {
        "id": "typescript-fix-class-property-missing-this",
        "title": "Fix the bug: a class property read without this",
        "prompt": "This class does not compile. What is wrong?",
        "level": "junior", "type": "fix", "subject": "types",
        "tags": ["typescript", "classes", "this", "fix"],
        "codeSnippet": "class Circle {\n  private radius: number;\n\n  constructor(radius) {\n    this.radius = radius;\n  }\n\n  calculateArea() {\n    return Math.PI * radius * radius;\n  }\n}",
        "options": [
            ("A", "calculateArea reads radius instead of this.radius, so it refers to no binding in scope", True,
             "Correct. Inside a method, a property must be reached through this — the bare name is not in scope."),
            ("B", "private properties cannot be read inside the class that declares them", False,
             "private means accessible only within the declaring class; reading it there is exactly what it is for."),
            ("C", "Math.PI must be imported before use", False,
             "Math is a global object available everywhere."),
            ("D", "The constructor cannot share a parameter name with a property", False,
             "That shadowing is legal and common; this.radius and radius are distinguishable."),
        ],
        "explanation": "Inside a method, a class property is not a variable in lexical scope — it lives on the instance and has to be reached through this. Writing radius makes the compiler look for a local or an outer binding, finds none, and errors. The fix is this.radius. Worth noting a second weakness: the constructor parameter has no annotation, so under noImplicitAny it is an implicit any; annotating it constructor(radius: number) tightens the class.",
        "interviewLine": "Class properties aren't in lexical scope inside methods — they're on the instance, so they need this.",
        "misconception": "Expecting a class body to behave like a closure where properties are ambient variables.",
        "hints": ["Where does the identifier radius resolve inside calculateArea?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-filter-truthy-vs-even",
        "title": "Fix the bug: a filter that keeps the wrong half",
        "prompt": "This is meant to keep the even numbers, but logs [1, 3, 5]. Why?",
        "level": "junior", "type": "fix", "subject": "types",
        "tags": ["typescript", "filter", "truthiness", "fix"],
        "codeSnippet": "const numbers: number[] = [1, 2, 3, 4, 5];\nconst evenNumbers = numbers.filter((num) => num % 2);\nconsole.log(evenNumbers);",
        "options": [
            ("A", "filter needs an explicit boolean return type annotation", False,
             "No annotation is required; filter accepts any predicate whose result is used for truthiness."),
            ("B", "num % 2 is 1 for odd numbers, which is truthy — so it keeps the odd ones", True,
             "Correct. The predicate must be num % 2 === 0."),
            ("C", "% returns a string, so every result is truthy", False,
             "% returns a number. If everything were truthy the whole array would come back."),
            ("D", "filter mutates the array, so the indices shift mid-iteration", False,
             "filter returns a new array and does not mutate the source."),
        ],
        "explanation": "num % 2 evaluates to 1 for odd numbers and 0 for even ones. filter keeps entries whose predicate is truthy, and 1 is truthy while 0 is falsy — so the odd numbers survive and the evens are dropped. The fix is to compare explicitly: num % 2 === 0. This is the classic cost of leaning on truthiness where a boolean was meant; TypeScript cannot catch it because a number is a perfectly valid thing to test for truthiness.",
        "interviewLine": "0 is falsy and 1 is truthy, so a bare modulo predicate keeps exactly the half you didn't want.",
        "misconception": "Reading num % 2 as 'is even'. It is the remainder, and the remainder for an even number is the falsy one.",
        "hints": ["What is 3 % 2, and is that value truthy?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-union-assignment-outside-type",
        "title": "Fix the bug: assigning outside a union",
        "prompt": "Which line fails to compile, and why?",
        "level": "junior", "type": "fix", "subject": "narrowing",
        "tags": ["typescript", "union-types", "assignability", "fix"],
        "codeSnippet": "let data: string | number;\ndata = \"Hello\";\ndata = 42;\ndata = true;",
        "options": [
            ("A", "data = 42 — a union can only hold its first member", False,
             "A union holds any one of its members; number is declared."),
            ("B", "data = \"Hello\" — a union needs a type assertion on assignment", False,
             "No assertion is needed to assign a declared member type."),
            ("C", "data = true — boolean is not a member of string | number", True,
             "Correct. A union permits exactly its declared members and nothing else."),
            ("D", "None — TypeScript widens the union on first assignment", False,
             "Explicitly annotated unions never widen. Only inferred types widen, and not to boolean."),
        ],
        "explanation": "string | number means the variable may hold a string or a number — those two and nothing more. Assigning true is an error because boolean is not a member. The union is not a starting point that grows as you assign; an explicit annotation fixes the set exactly. To allow booleans you have to say so: string | number | boolean.",
        "interviewLine": "A union is a closed set. It doesn't widen to accommodate whatever you assign next.",
        "misconception": "Expecting a union to expand on assignment the way an inferred let does.",
        "hints": ["Which of the three assigned values is not named in the annotation?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-factorial-loop-multiplies-by-zero",
        "title": "Fix the bug: a factorial that always returns 0",
        "prompt": "factorial(5) returns 0. What is wrong with the loop?",
        "level": "intermediate", "type": "fix", "subject": "types",
        "tags": ["typescript", "loops", "off-by-one", "fix"],
        "codeSnippet": "function factorial(n: number): number {\n  let result = 1;\n  for (let i = n; i >= 0; i--) {\n    result = result * i;\n  }\n  return result;\n}",
        "options": [
            ("A", "The condition i >= 0 lets the loop reach 0, so the running product is multiplied by zero", True,
             "Correct. Every accumulated value is wiped out on the final iteration. It should be i > 0."),
            ("B", "result should start at 0 rather than 1", False,
             "Starting at 0 would make every product 0 too. A multiplicative accumulator starts at 1."),
            ("C", "The loop counts down, and factorial must be computed upward", False,
             "Direction is irrelevant to a product — counting down is fine."),
            ("D", "n is not validated as a non-negative integer", False,
             "A real weakness, but not the reason factorial(5) returns 0."),
        ],
        "explanation": "The loop runs while i >= 0, so its last iteration multiplies the accumulated product by 0 and discards all the work. Changing the condition to i > 0 stops at 1 and yields 120 for n = 5. Guarding the input separately is still worth doing — negative n makes the loop body never execute and silently return 1 — but the bug that produces 0 is the termination condition.",
        "interviewLine": "A multiplicative accumulator must never reach zero. The termination condition is the whole bug.",
        "misconception": "Blaming the initial value of result. Starting at 1 is correct for a product.",
        "hints": ["Write out the values i takes for n = 5. What is the last one?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-any-return-type-loses-information",
        "title": "Fix the weakness: a function that knows more than it declares",
        "prompt": "This function works correctly at runtime. What should be improved about its types?",
        "level": "intermediate", "type": "fix", "subject": "types",
        "tags": ["typescript", "any", "return-types", "fix"],
        "codeSnippet": "function keepNumbers(miscData: any[]): any[] {\n  const numbers: any[] = [];\n  for (let value of miscData) {\n    value = parseFloat(value);\n    if (!isNaN(value)) {\n      numbers.push(value);\n    }\n  }\n  return numbers;\n}\n\nconst onlyNumbers = keepNumbers([1, 2, \"hello\", 4.56, \"78\", null]);",
        "options": [
            ("A", "The parameter should be unknown[] and the body left otherwise unchanged", False,
             "unknown[] is a fair choice for the input, but the real loss is on the way out."),
            ("B", "The return type should be number[] — the function guarantees it, but declares any[] and throws it away", True,
             "Correct. Callers get any back and lose all checking on the result."),
            ("C", "parseFloat should be Number, otherwise the values are strings", False,
             "parseFloat returns a number. The two differ on edge cases, not on the resulting type."),
            ("D", "for...of cannot iterate an array typed any[]", False,
             "for...of iterates any array regardless of element type."),
        ],
        "explanation": "The function does the work to guarantee an array of numbers — it parses each value and rejects anything that is NaN — and then declares any[] on the way out, discarding that guarantee. Every caller now holds an any[] and can call string methods on the elements without complaint. Declaring number[] pushes the knowledge back to the call site. Tightening the input to unknown[] is a further improvement, since it forces the parsing that the body already does.",
        "interviewLine": "If a function guarantees something, its return type should say so. any on the way out throws away the work the body just did.",
        "misconception": "Treating any as a harmless placeholder. It silently disables checking for everyone downstream.",
        "hints": ["What can a caller do with the result that they should not be able to?"],
        "minutes": 3,
    },
    {
        "id": "typescript-fix-class-fields-not-declared",
        "title": "Fix the bug: assigning to properties a class never declared",
        "prompt": "This class does not compile. What is missing?",
        "level": "intermediate", "type": "fix", "subject": "types",
        "tags": ["typescript", "classes", "properties", "fix"],
        "codeSnippet": "class Car {\n  constructor(make: string, model: string, year: number) {\n    this.make = make;\n    this.model = model;\n    this.year = year;\n  }\n\n  getInfo(): string {\n    return `${this.make} ${this.model} (${this.year})`;\n  }\n}",
        "options": [
            ("A", "The class needs an explicit return type on the constructor", False,
             "Constructors never declare a return type."),
            ("B", "The properties are never declared, so this.make and the others do not exist on the type", True,
             "Correct. Either declare the fields, or use parameter properties to declare and assign in one step."),
            ("C", "getInfo cannot use a template literal with numeric values", False,
             "Template literals interpolate numbers without complaint."),
            ("D", "Constructor parameters must be optional to be assignable to properties", False,
             "Optionality is unrelated to whether a property exists on the class."),
        ],
        "explanation": "Unlike JavaScript, TypeScript requires class fields to be declared before you assign to them — the type of an instance is defined by its declarations, not inferred from what the constructor happens to set. Either declare make: string; model: string; year: number; above the constructor, or collapse the whole thing using parameter properties: constructor(public make: string, public model: string, public year: number) {}, which declares and assigns in one step.",
        "interviewLine": "An instance's type comes from its declared fields, not from whatever the constructor assigns. Parameter properties collapse both into one line.",
        "misconception": "Carrying the JavaScript habit of creating properties by assigning to this in the constructor.",
        "hints": ["What does the compiler know about the shape of a Car instance from reading the class body?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-class-members-separated-by-commas",
        "title": "Fix the bug: commas between class members",
        "prompt": "This class fails to parse. What is the syntax error?",
        "level": "senior", "type": "fix", "subject": "types",
        "tags": ["typescript", "classes", "syntax", "fix"],
        "codeSnippet": "class Person {\n  name: string,\n  age: number,\n\n  constructor(name: string, age: number) {\n    this.name = name;\n    this.age = age;\n  }\n}",
        "options": [
            ("A", "Class members are separated by semicolons or newlines, not commas", True,
             "Correct. Commas separate members of an object literal or an interface written inline — not a class body."),
            ("B", "Property declarations must carry an access modifier such as public", False,
             "Members are public by default; the modifier is optional."),
            ("C", "The constructor must be declared before any property", False,
             "Members may appear in any order."),
            ("D", "Properties must be initialised where they are declared", False,
             "Assigning them in the constructor satisfies definite assignment under strictPropertyInitialization."),
        ],
        "explanation": "A class body is not an object literal. Members are terminated by semicolons or simply by newlines, and a comma is a syntax error. The confusion is understandable — type literals and interfaces do accept commas between members — but class bodies follow JavaScript class syntax. Removing the commas is the whole fix.",
        "interviewLine": "Class bodies use JavaScript class syntax, not object-literal syntax. Commas belong in the latter.",
        "misconception": "Carrying interface or object-literal punctuation into a class body.",
        "hints": ["Would this punctuation be valid inside an interface?"],
        "minutes": 2,
    },
    {
        "id": "typescript-fix-sum-array-off-by-one",
        "title": "Fix the bug: a sum that returns NaN",
        "prompt": "sumArray([1, 2, 3]) returns NaN. Why?",
        "level": "senior", "type": "fix", "subject": "types",
        "tags": ["typescript", "arrays", "off-by-one", "fix"],
        "codeSnippet": "function sumArray(arr: number[]): number {\n  let sum = 0;\n  for (let i = 1; i <= arr.length; i++) {\n    sum += arr[i];\n  }\n  return sum;\n}",
        "options": [
            ("A", "sum should be initialised to arr[0] rather than 0", False,
             "That would paper over the real bug, and still read past the end."),
            ("B", "The loop skips index 0 and reads arr[length], which is undefined — adding it gives NaN", True,
             "Correct. It should run from i = 0 while i < arr.length."),
            ("C", "arr[i] returns a string, so += concatenates", False,
             "The array is typed number[]; the out-of-range read yields undefined, not a string."),
            ("D", "+= cannot be used to accumulate numbers in a typed array loop", False,
             "+= is fine. The bug is entirely in the bounds."),
        ],
        "explanation": "Two errors compound in one line. Starting at i = 1 skips the first element, and running while i <= arr.length reads one past the end. Indexing beyond the end returns undefined, and 6 + undefined is NaN — so the result is not merely wrong, it is not a number at all. The correct bounds are i = 0 and i < arr.length. TypeScript does not catch this: arr[i] is typed number regardless of whether i is in range, unless noUncheckedIndexedAccess is enabled.",
        "interviewLine": "Indexing past the end gives undefined, and any arithmetic on undefined gives NaN — which is why an off-by-one shows up as NaN rather than a slightly wrong total.",
        "misconception": "Trusting that arr[i] is a number because the array is number[]. Without noUncheckedIndexedAccess, out-of-range reads are still typed number.",
        "hints": ["Which indices does the loop actually visit for a 3-element array?"],
        "minutes": 2,
    },

    # ------------------------------------------------- correct-as-written traps
    {
        "id": "typescript-spread-object-typed-parameters",
        "title": "Spreading a value typed as object",
        "prompt": "Does this compile, and what is the weakness in its typing?",
        "level": "senior", "type": "fix", "subject": "types",
        "tags": ["typescript", "spread", "object-type", "generics", "fix"],
        "codeSnippet": "function mergeObjects(obj1: object, obj2: object): object {\n  return { ...obj1, ...obj2 };\n}\n\nconst merged = mergeObjects({ name: \"John\" }, { age: 30 });",
        "options": [
            ("A", "It fails: the object type does not permit spreading", False,
             "Spreading a value typed object is perfectly legal TypeScript."),
            ("B", "It compiles, but the object return type loses both shapes — merged has no known properties", True,
             "Correct. Generics would preserve them: <A, B>(a: A, b: B): A & B."),
            ("C", "It fails: a function cannot return an object literal built from spreads", False,
             "It can. The literal is a perfectly ordinary expression."),
            ("D", "It compiles and merged is correctly typed as { name: string; age: number }", False,
             "The declared return type is object, so the specific shape is discarded at the boundary."),
        ],
        "explanation": "The code compiles — object simply means 'any non-primitive', and spreading such a value is allowed. The weakness is at the boundary: declaring the return type as object throws away everything the compiler knew, so merged.name is an error even though the value is there. Making the function generic keeps the information: function mergeObjects<A extends object, B extends object>(a: A, b: B): A & B. Now the caller gets the intersection and the properties are visible.",
        "interviewLine": "object means 'not a primitive' and nothing more. If you want the caller to keep the shape, the function has to be generic.",
        "misconception": "Believing the object type blocks spreading. It permits it — it just erases the result's shape.",
        "hints": ["Try reading merged.name at the call site. Why does that fail?"],
        "minutes": 3,
    },
    {
        "id": "typescript-generic-class-dictionary-correct",
        "title": "Reading a generic class that is already correct",
        "prompt": "What, if anything, is wrong with this generic Dictionary?",
        "level": "intermediate", "type": "fix", "subject": "generics",
        "tags": ["typescript", "generics", "index-signature", "fix"],
        "codeSnippet": "class Dictionary<T> {\n  private data: { [key: string]: T } = {};\n\n  setValue(key: string, value: T): void {\n    this.data[key] = value;\n  }\n\n  getValue(key: string): T | undefined {\n    return this.data[key];\n  }\n}\n\nconst myDict = new Dictionary<number>();\nmyDict.setValue(\"one\", 1);",
        "options": [
            ("A", "getValue should return T, not T | undefined", False,
             "T | undefined is the honest type — a missing key really does yield undefined."),
            ("B", "An index signature cannot be used on a private field", False,
             "Visibility and index signatures are independent."),
            ("C", "Nothing is wrong; the class is correctly typed, and T | undefined honestly reflects a missing key", True,
             "Correct. Not every 'find the bug' question has a bug — and this one models optionality properly."),
            ("D", "T must be constrained with extends to be usable in an index signature", False,
             "An unconstrained T is fine as an index signature's value type."),
        ],
        "explanation": "This class is correct. The index signature { [key: string]: T } models a string-keyed store, T threads the element type through both methods, and getValue returning T | undefined is the accurate signature — looking up an absent key genuinely yields undefined, and saying so forces callers to handle it. Declaring T would have been the mistake. Worth knowing: an index signature is what noUncheckedIndexedAccess would otherwise add the undefined to automatically.",
        "interviewLine": "T | undefined on a lookup isn't defensive noise — it's the truth about a key that might not be there.",
        "misconception": "Assuming every debugging question contains a bug, and 'fixing' a correct signature into a dishonest one.",
        "hints": ["What does this.data[key] actually evaluate to for a key that was never set?"],
        "minutes": 2,
    },
    {
        "id": "typescript-numeric-enum-comparison-correct",
        "title": "Reading a numeric enum that is already correct",
        "prompt": "Is there a logical error in this enum and the function that uses it?",
        "level": "senior", "type": "fix", "subject": "types",
        "tags": ["typescript", "enums", "fix"],
        "codeSnippet": "enum DaysOfTheWeek {\n  Sunday,\n  Monday,\n  Tuesday,\n  Wednesday,\n  Thursday,\n  Friday,\n  Saturday,\n}\n\nfunction getWorkingDay(day: DaysOfTheWeek): string {\n  if (day === DaysOfTheWeek.Saturday || day === DaysOfTheWeek.Sunday) {\n    return \"Weekend\";\n  }\n  return \"Weekday\";\n}",
        "options": [
            ("A", "Sunday is 0, which is falsy, so the comparison against it never matches", False,
             "The comparison uses === against the member, not a truthiness test, so 0 compares correctly."),
            ("B", "Nothing is wrong — members auto-number from 0 and the comparisons are exact", True,
             "Correct. The one thing to know is that a plain numeric enum accepts any number at the boundary."),
            ("C", "Enum members must be given explicit values to be comparable", False,
             "Numeric enums auto-number from 0; explicit values are optional."),
            ("D", "getWorkingDay must handle every member with a switch to be exhaustive", False,
             "The early return plus fallthrough covers all cases; exhaustiveness is not required here."),
        ],
        "explanation": "The code is correct. Members auto-number from 0, so Sunday is 0 and Saturday is 6, and === compares those numbers exactly — the falsiness of 0 never comes into it. The real caveat with numeric enums is at the boundary: they are not nominal, so getWorkingDay(99) type-checks even though 99 is not a member. A string enum, or a union of string literals, closes that hole and survives serialisation more legibly.",
        "interviewLine": "Numeric enums auto-number from 0 and compare exactly — but they don't reject out-of-range numbers, which is why string literal unions are often the safer choice.",
        "misconception": "Worrying that Sunday being 0 breaks the comparison. It would matter for a truthiness check, not for ===.",
        "hints": ["Does === care whether one of the values happens to be falsy?"],
        "minutes": 2,
    },
    {
        "id": "typescript-private-field-encapsulation-correct",
        "title": "Reading an encapsulated class that is already correct",
        "prompt": "Does this BankAccount contain a logical error?",
        "level": "intermediate", "type": "fix", "subject": "types",
        "tags": ["typescript", "classes", "encapsulation", "fix"],
        "codeSnippet": "class BankAccount {\n  private balance: number;\n\n  constructor(initialBalance: number) {\n    this.balance = initialBalance;\n  }\n\n  deposit(amount: number): void {\n    this.balance += amount;\n  }\n\n  getBalance(): number {\n    return this.balance;\n  }\n}",
        "options": [
            ("A", "getBalance leaks the private field and should return a copy", False,
             "balance is a number — a primitive, copied by value. There is no reference to leak."),
            ("B", "private is erased at compile time, so the field is not really private", False,
             "True of private but irrelevant to whether this code is logically correct. #balance would enforce it at runtime."),
            ("C", "balance must be initialised at its declaration site", False,
             "Assigning it in the constructor satisfies strictPropertyInitialization."),
            ("D", "Nothing is wrong — the field is encapsulated and both methods are correctly typed", True,
             "Correct. The only thing worth adding is validation that amount is positive, which is a design choice rather than a bug."),
        ],
        "explanation": "The class is correct: balance is private so it can only be touched inside the class, the constructor initialises it, and both methods are accurately typed. The improvements available are about policy rather than correctness — rejecting a negative deposit, or using the ECMAScript #balance form, which is enforced at runtime instead of being erased with the types. Neither is a bug in what is written.",
        "interviewLine": "TypeScript's private is a compile-time check that's erased; #private is a runtime guarantee. Different tools for different threats.",
        "misconception": "Assuming a returned private field needs defensive copying. That matters for mutable objects, not primitives.",
        "hints": ["Is balance a value or a reference?"],
        "minutes": 2,
    },
]
