"""
Authored from "17 React Interview Questions You Must Know as a Developer in
2025" (DEV Community), minus the seven that duplicate questions already in the
bank.
"""

SOURCE = "react-17-2025"
CATEGORY = "react"
LANG = "tsx"

QUESTIONS = [
    {
        "id": "react-virtual-dom-vs-real-and-shadow-dom",
        "title": "Virtual DOM, real DOM and Shadow DOM are three different things",
        "prompt": "How does React's Virtual DOM differ from the real DOM and from the Shadow DOM?",
        "level": "junior",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "virtual-dom", "shadow-dom", "reconciliation"],
        "codeSnippet": None,
        "options": [
            ("A", "The Virtual DOM is an in-memory description of the UI that React diffs before touching the real DOM; the Shadow DOM is an unrelated browser feature for encapsulating a component's markup and styles", True,
             "Correct. One is a React implementation detail, the other is a native browser API — they only sound alike."),
            ("B", "The Virtual DOM and the Shadow DOM are the same mechanism, named differently by React and by browser vendors", False,
             "They are unrelated. The Shadow DOM is a Web Components API that React does not use for rendering."),
            ("C", "The Virtual DOM is a faster reimplementation of the real DOM that React renders to directly", False,
             "React never renders to the Virtual DOM as an output target — it eventually commits to the real DOM."),
            ("D", "The Shadow DOM is what React diffs, and the Virtual DOM is the browser's internal render tree", False,
             "This inverts both. React diffs its own Virtual DOM; the browser's internal structures are not the Shadow DOM."),
        ],
        "explanation": "The Virtual DOM is a plain-object description of what the UI should look like, kept in memory. React builds a new one on each render, diffs it against the previous one, and applies only the differences to the real DOM — batching the expensive part. The Shadow DOM is something else entirely: a native browser API that gives an element its own encapsulated subtree and scoped styles, used by Web Components. React does not use it to render.",
        "interviewLine": "The Virtual DOM is React's diffing strategy; the Shadow DOM is the browser's encapsulation strategy. Same word, unrelated ideas.",
        "misconception": "Assuming Virtual DOM and Shadow DOM are two names for the same thing because both contrast with 'the real DOM'.",
        "hints": ["One of the three is a browser standard that has nothing to do with React."],
        "minutes": 2,
    },
    {
        "id": "react-class-vs-function-components-today",
        "title": "Which component type to reach for in new code",
        "prompt": "React has class components and function components. Which should new code use, and why?",
        "level": "junior",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "components", "hooks", "function-components"],
        "codeSnippet": None,
        "options": [
            ("A", "Class components, because only they can hold state", False,
             "Function components have held state since hooks arrived in React 16.8."),
            ("B", "Function components, because hooks gave them state and effects and they are now the default for new code", True,
             "Correct. Classes still work and are not deprecated, but everything new — including Server Components — is built around functions."),
            ("C", "Function components for presentation only; anything stateful must still be a class", False,
             "That was true before hooks. It has not been true since React 16.8."),
            ("D", "Class components, because function components re-render more often", False,
             "Both re-render on the same triggers. Component type has no bearing on render frequency."),
        ],
        "explanation": "Before hooks, function components were limited to presentation and anything stateful had to be a class. Hooks removed that split: useState, useEffect and the rest give function components the full feature set, with less ceremony and no this binding. Class components are not deprecated and still hold one unique capability — error boundaries need componentDidCatch or getDerivedStateFromError — but new code should default to functions.",
        "interviewLine": "Hooks collapsed the class/function split. The only thing still requiring a class is an error boundary.",
        "misconception": "Believing function components are still 'presentational only'. That distinction ended with hooks.",
        "hints": ["Is there anything a class can still do that a function cannot?"],
        "minutes": 2,
    },
    {
        "id": "react-keys-outside-lists-force-remount",
        "title": "Keys work outside lists too — and that is how you force a remount",
        "prompt": "Keys are usually seen on list items. What happens if you put a changing key on a single element?",
        "level": "intermediate",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "keys", "reconciliation", "remount"],
        "codeSnippet": "const Profile = ({ userId }: { userId: string }) => {\n  // changing userId throws away all internal state\n  return <ProfileForm key={userId} userId={userId} />;\n};",
        "options": [
            ("A", "Nothing — keys are ignored outside of a list", False,
             "Keys are part of reconciliation for every element, not just list children."),
            ("B", "React warns in development and falls back to positional matching", False,
             "There is no warning; a key on a single element is entirely valid."),
            ("C", "React treats it as a different element and remounts it, discarding its state", True,
             "Correct. A changed key means a different identity, so the old instance unmounts and a fresh one mounts with reset state."),
            ("D", "React reuses the instance but re-runs every effect", False,
             "It does not reuse the instance at all — the component unmounts and a new one mounts."),
        ],
        "explanation": "Keys tell React which element a node corresponds to between renders. In a list that prevents index-based mismatching, but the mechanism is general: change an element's key and React concludes it is a different element, so it unmounts the old instance — losing all its state — and mounts a new one. That makes a changing key the idiomatic way to reset a form or a component when its subject changes, rather than syncing state in an effect.",
        "interviewLine": "A key is an identity claim. Change the identity and React remounts — which is the cleanest way to reset state on a prop change.",
        "misconception": "Thinking keys only matter inside .map(). They control reconciliation identity everywhere.",
        "hints": ["What does React do when it decides an element is not the same element as last time?"],
        "minutes": 2,
    },
    {
        "id": "react-why-jsx-needs-transpiling",
        "title": "What JSX actually compiles to",
        "prompt": "Why does JSX have to be transpiled before a browser can run it?",
        "level": "junior",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "jsx", "babel", "transpilation"],
        "codeSnippet": "const Greeting = () => <h1 className=\"greeting\">Hello</h1>;\n\n// becomes, roughly:\nconst Greeting = () =>\n  jsx(\"h1\", { className: \"greeting\", children: \"Hello\" });",
        "options": [
            ("A", "Because JSX is not valid JavaScript syntax — a compiler rewrites it into plain function calls", True,
             "Correct. No engine parses JSX; Babel, SWC or TypeScript rewrite each element into a function call that returns a plain object."),
            ("B", "Because browsers can parse JSX but do so too slowly for production", False,
             "No browser parses JSX at all — it is a syntax error in every JavaScript engine."),
            ("C", "Because JSX must be converted into HTML strings before rendering", False,
             "It compiles into function calls returning objects, not HTML strings. React builds DOM nodes from those objects."),
            ("D", "Because transpiling is how React escapes interpolated values against XSS", False,
             "Escaping happens at render time in React, not during transpilation."),
        ],
        "explanation": "JSX is a syntax extension, not JavaScript. No engine can parse <h1>Hello</h1>, so a compiler rewrites every element into a function call — createElement under the classic transform, jsx under the modern automatic runtime. Those calls return plain objects describing the UI, which is exactly the Virtual DOM React then diffs. This is also why JSX expressions are just values: you can store them in variables and return them from functions.",
        "interviewLine": "JSX is sugar over function calls that return objects. The compiler is what turns markup-shaped syntax into those calls.",
        "misconception": "Thinking JSX compiles to HTML. It compiles to function calls that produce JavaScript objects.",
        "hints": ["What would a JavaScript engine do if you handed it an angle bracket in expression position?"],
        "minutes": 2,
    },
    {
        "id": "react-styling-approaches-tradeoffs",
        "title": "Choosing a styling approach in React",
        "prompt": "Which statement about styling React components is accurate?",
        "level": "junior",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "styling", "css-modules", "inline-styles"],
        "codeSnippet": "<div style={{ backgroundColor: \"blue\", color: \"white\" }} />",
        "options": [
            ("A", "Inline style objects support the full range of CSS, including pseudo-classes and media queries", False,
             "Inline styles cannot express :hover, ::before or media queries — those need a real stylesheet."),
            ("B", "CSS Modules scope class names per file, avoiding the global collisions a plain stylesheet risks", True,
             "Correct. The build step rewrites each class to a unique name, giving you real CSS with local scope."),
            ("C", "A plain imported .css file is automatically scoped to the importing component", False,
             "A plain stylesheet is global no matter where it is imported; only Modules scope it."),
            ("D", "Inline styles perform best because they avoid stylesheet parsing", False,
             "Inline style objects are recreated every render and cannot be cached or reused by the browser like a stylesheet."),
        ],
        "explanation": "Plain CSS files give you every CSS feature but are global, so class names can collide across a codebase. CSS Modules keep real CSS while the build step rewrites each class name to something unique per file, which gets you scoping for free. Inline style objects are genuinely scoped to one element but cannot express pseudo-classes, pseudo-elements or media queries, and a new object each render is not something the browser can cache.",
        "interviewLine": "Inline styles scope but can't do :hover or media queries; CSS Modules give you real CSS with local scope. Pick per constraint, not per fashion.",
        "misconception": "Assuming importing a .css file into a component scopes it to that component. It does not.",
        "hints": ["Which approach cannot express a hover state?"],
        "minutes": 2,
    },
    {
        "id": "react-error-boundaries-what-they-catch",
        "title": "What an error boundary can and cannot catch",
        "prompt": "You wrap a subtree in an error boundary. Which failure does it NOT catch?",
        "level": "intermediate",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "error-boundaries", "error-handling"],
        "codeSnippet": "class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() {\n    return { hasError: true };\n  }\n  componentDidCatch(error, info) {\n    log(error, info);\n  }\n  render() {\n    return this.state.hasError ? <Fallback /> : this.props.children;\n  }\n}",
        "options": [
            ("A", "An error thrown while rendering a child component", False,
             "Render-phase errors are exactly what error boundaries exist to catch."),
            ("B", "An error thrown inside a child's useEffect during commit", False,
             "Errors thrown from lifecycle and effect code in the subtree are caught."),
            ("C", "A rejected promise in an async click handler", True,
             "Correct. Event handlers run outside the render/commit phases, so their errors escape the boundary — catch them yourself."),
            ("D", "An error thrown from a child's constructor", False,
             "Constructor errors happen during rendering and are caught."),
        ],
        "explanation": "Without a boundary, an error during rendering unmounts the whole tree — React would rather show nothing than something wrong. An error boundary catches errors thrown while rendering, in lifecycle methods, and in constructors anywhere below it, and swaps in a fallback. It does not catch errors in event handlers, in asynchronous code such as setTimeout or a rejected promise, or in the boundary's own render — those are outside the render/commit path and need ordinary try/catch. Error boundaries still require a class, or a wrapper like react-error-boundary.",
        "interviewLine": "Error boundaries catch the render path, not the interaction path. A failing click handler needs its own try/catch.",
        "misconception": "Expecting a boundary to catch everything inside it. Event handlers and async callbacks are not covered.",
        "hints": ["Which of these runs outside the render and commit phases?"],
        "minutes": 3,
    },
    {
        "id": "react-lifecycle-methods-as-effects",
        "title": "Expressing the class lifecycle with useEffect",
        "prompt": "Which useEffect corresponds to componentDidUpdate for a single value, without also firing on mount?",
        "level": "intermediate",
        "type": "concept",
        "subject": "hooks",
        "tags": ["react", "useEffect", "lifecycle", "hooks"],
        "codeSnippet": "useEffect(() => {\n  console.log(\"mounted\");\n  return () => console.log(\"unmounted\");\n}, []);\n\nuseEffect(() => {\n  console.log(\"count changed\");\n}, [count]);",
        "options": [
            ("A", "useEffect(fn, [count]) — it fires only when count changes", False,
             "It also fires once after the initial mount, which componentDidUpdate does not."),
            ("B", "useEffect(fn) with no dependency array", False,
             "That runs after every render, including the first — closer to componentDidUpdate plus componentDidMount plus more."),
            ("C", "There is no exact equivalent; you need a ref to skip the first run", True,
             "Correct. Every effect runs after the initial mount, so 'updates only' requires tracking that yourself."),
            ("D", "useEffect(fn, []) — the empty array means updates only", False,
             "An empty array is the opposite: it runs once on mount and never again."),
        ],
        "explanation": "useEffect(fn, []) maps cleanly onto componentDidMount, and its cleanup function onto componentWillUnmount. componentDidUpdate has no exact equivalent, because every effect also runs after the initial mount — useEffect(fn, [count]) fires on mount and on each change. Skipping the first run means holding a ref and checking it. That friction is deliberate: effects are meant to synchronise with external systems based on current values, not to re-enact lifecycle hooks.",
        "interviewLine": "Effects synchronise, they don't sequence. There's no 'on update only' because an effect doesn't care whether this is the first render.",
        "misconception": "Assuming a dependency array means 'only when this changes'. It means 'after every render where this changed' — and the mount always counts.",
        "hints": ["Does an effect with dependencies skip the very first render?"],
        "minutes": 3,
    },
    {
        "id": "react-refs-persist-without-rerender",
        "title": "What separates a ref from state",
        "prompt": "What is the defining difference between useRef and useState?",
        "level": "junior",
        "type": "concept",
        "subject": "hooks",
        "tags": ["react", "useRef", "useState", "hooks"],
        "codeSnippet": "const inputRef = useRef<HTMLInputElement>(null);\nconst focus = () => inputRef.current?.focus();\n\nreturn <input ref={inputRef} />;",
        "options": [
            ("A", "Refs persist across renders but changing one does not trigger a re-render", True,
             "Correct. That is the whole distinction — same persistence, no subscription."),
            ("B", "Refs are reset on every render while state persists", False,
             "Both persist for the lifetime of the component; the ref object is stable."),
            ("C", "Refs can only hold DOM nodes", False,
             "A ref holds any mutable value. DOM nodes are just the most common use."),
            ("D", "Refs are read-only once assigned", False,
             "ref.current is freely mutable — that is the point."),
        ],
        "explanation": "Both useRef and useState survive re-renders. The difference is that React subscribes to state: setting it schedules a render. A ref is a plain mutable box — writing ref.current changes the value immediately and React never notices. That makes refs right for values the UI does not display: a DOM node to focus, a timer id to clear, the previous value of a prop. It also makes them wrong for anything the render output depends on, because nothing will re-render to show the change.",
        "interviewLine": "Both survive renders; only state causes one. If the UI needs to react to it, it's state — otherwise it's a ref.",
        "misconception": "Reaching for a ref to avoid re-renders on a value the UI actually displays, then wondering why the screen is stale.",
        "hints": ["Both persist. What does React do differently when each one changes?"],
        "minutes": 2,
    },
    {
        "id": "react-optimization-techniques-when-they-help",
        "title": "When memoization actually helps",
        "prompt": "Which use of memoization is genuinely worthwhile?",
        "level": "intermediate",
        "type": "concept",
        "subject": "performance",
        "tags": ["react", "useMemo", "memo", "performance", "optimization"],
        "codeSnippet": "const filtered = useMemo(\n  () => hugeList.filter((x) => x.active),\n  [hugeList],\n);",
        "options": [
            ("A", "Wrapping every component in React.memo as a matter of course", False,
             "Each memo adds a props comparison on every render. Applied blindly it costs more than it saves."),
            ("B", "useMemo around an expensive computation whose inputs rarely change", True,
             "Correct. Real work, stable inputs — that is where the cache pays for itself."),
            ("C", "useMemo around a simple arithmetic expression to avoid recomputing it", False,
             "Reading the cache costs more than the arithmetic. This is strictly slower."),
            ("D", "useCallback on every function, so children never see a new reference", False,
             "Only helps if the child is memoised and actually re-renders measurably. Otherwise it is overhead plus noise."),
        ],
        "explanation": "Memoization trades memory and comparison cost for skipped work, so it only wins when the skipped work is genuinely expensive and the inputs are genuinely stable. useMemo around a real computation over a large list qualifies. Wrapping trivial expressions does not — the bookkeeping costs more than recomputing. React.memo and useCallback only pay off together, on a component that would otherwise re-render often with unchanged props. Measure first; most render cost turns out to be somewhere else.",
        "interviewLine": "Memoization isn't free — you're trading comparison cost for computation cost. It only wins when the computation is the expensive half.",
        "misconception": "Treating useMemo and React.memo as free speedups to apply everywhere.",
        "hints": ["What does the memoization itself cost on every render?"],
        "minutes": 3,
    },
    {
        "id": "react-portals-dom-vs-react-tree",
        "title": "What a portal does and does not move",
        "prompt": "A modal is rendered through createPortal into a node outside its parent. Where do its click events propagate?",
        "level": "intermediate",
        "type": "concept",
        "subject": "rendering-keys",
        "tags": ["react", "portals", "events", "dom"],
        "codeSnippet": "const Modal = ({ children }: { children: React.ReactNode }) =>\n  createPortal(children, document.getElementById(\"portal-root\")!);",
        "options": [
            ("A", "Up the DOM tree from the portal's host node, bypassing the React parent", False,
             "React events follow the React tree, not the DOM position of the host node."),
            ("B", "Up the React tree to the component that rendered the portal, despite the DOM position", True,
             "Correct. A portal relocates the DOM node only; context and event bubbling still follow the React tree."),
            ("C", "Nowhere — portals stop event propagation entirely", False,
             "Events propagate normally; the portal changes where the node lives, not whether events bubble."),
            ("D", "To both trees simultaneously, so handlers fire twice", False,
             "Handlers fire once, following the React tree."),
        ],
        "explanation": "createPortal changes where a subtree is inserted in the DOM — useful for modals and tooltips that must escape a parent's overflow or stacking context — but it does not move the component in the React tree. Context still flows down from the rendering parent, and events still bubble up to it, which is what makes a portalled modal feel like a normal child despite living elsewhere in the document. Only the physical DOM position changes.",
        "interviewLine": "A portal moves the node, not the component. Context and events still follow the React tree.",
        "misconception": "Expecting a portalled child to lose context or bubble to its DOM host. Both follow the React tree.",
        "hints": ["Does the portal change the component hierarchy, or only the DOM placement?"],
        "minutes": 2,
    },
]
