"""
Authored from "12 Tricky TypeScript Questions That Separate Good Developers
From Great Ones" (DEV Community). Senior-level type-system material.

Distractors are written from the misconception each question actually targets,
not from a reusable template.
"""

SOURCE = "tricky-typescript-12"
LEVEL = "senior"
CATEGORY = "typescript"
LANG = "typescript"

QUESTIONS = [
    {
        "id": "typescript-ambient-declaration-global-constant",
        "title": "Declaring a global constant that survives being included twice",
        "prompt": "You need a globally accessible constant in a .d.ts-style setup where the same file may be processed more than once. Which declaration is correct?",
        "subject": "types",
        "tags": ["typescript", "declarations", "ambient", "senior"],
        "codeSnippet": None,
        "options": [
            ("A", "declare const API_VERSION: string;", True,
             "Correct. An ambient declaration asserts the symbol exists at runtime without emitting any JavaScript, so processing the file twice cannot produce a duplicate definition."),
            ("B", "const API_VERSION: string = '1.0';", False,
             "A plain const emits code. If the file is concatenated or included twice you get a redeclaration error."),
            ("C", "export const API_VERSION: string = '1.0';", False,
             "export creates a module-scoped binding. It is not global — consumers must import it."),
            ("D", "globalThis.API_VERSION = '1.0';", False,
             "This is a runtime assignment only. It gives you no compile-time type, no declaration merging, and no checking."),
        ],
        "explanation": "declare const introduces an ambient declaration: it tells the compiler a symbol exists at runtime without emitting any JavaScript for it. That is what makes it safe when the same file is processed more than once, as with legacy --outFile builds or script concatenation. A plain const emits code and can collide; export const is module-scoped rather than global; assigning to globalThis is a runtime-only trick with no type safety.",
        "interviewLine": "declare says 'this exists, trust me' — it types a symbol without emitting it, which is exactly what a global constant in a declaration file needs.",
        "misconception": "Assuming declare and const are interchangeable. declare emits nothing; const emits a binding, and a binding declared twice is an error.",
        "hints": ["Which of these produces no JavaScript output at all?"],
        "minutes": 2,
    },
    {
        "id": "typescript-as-const-literal-widening",
        "title": "What as const does to inferred literal types",
        "prompt": "What is the inferred type of config?",
        "subject": "types",
        "tags": ["typescript", "as-const", "literal-types", "senior"],
        "codeSnippet": "const config = { apiUrl: 'https://api.example.com', timeout: 5000 } as const;",
        "options": [
            ("A", "{ apiUrl: string; timeout: number }", False,
             "That is the type you get WITHOUT as const — TypeScript widens the literals to their base types."),
            ("B", "{ readonly apiUrl: 'https://api.example.com'; readonly timeout: 5000 }", True,
             "Correct. as const narrows each value to its literal type and marks every property readonly."),
            ("C", "{ readonly apiUrl: string; readonly timeout: number }", False,
             "as const does add readonly, but it also prevents the literal widening — the values keep their exact types."),
            ("D", "Readonly<Record<string, string | number>>", False,
             "as const preserves the exact keys and exact literal values; it does not collapse them into an index signature."),
        ],
        "explanation": "as const does two things at once: it stops literal widening, so 'https://api.example.com' stays that exact string literal type rather than widening to string, and it marks every property readonly. Without it TypeScript infers { apiUrl: string; timeout: number }. The narrow literal types are what make exhaustive checks and discriminated unions work off a plain object.",
        "interviewLine": "as const freezes both the value and the type — readonly properties and literal types instead of widened ones.",
        "misconception": "Thinking as const only adds readonly. The bigger effect is that it stops literal widening.",
        "hints": ["It changes two things about every property: mutability and how precise the type is."],
        "minutes": 2,
    },
    {
        "id": "typescript-type-predicate-vs-boolean",
        "title": "Why a boolean return type does not narrow",
        "prompt": "Both functions have identical runtime behaviour. Why does only isString2 narrow value inside the if?",
        "subject": "narrowing",
        "tags": ["typescript", "type-guards", "narrowing", "senior"],
        "codeSnippet": "function isString1(val: unknown): boolean {\n  return typeof val === 'string';\n}\n\nfunction isString2(val: unknown): val is string {\n  return typeof val === 'string';\n}\n\nfunction process(value: string | number) {\n  if (isString1(value)) {\n    value.toUpperCase(); // error\n  }\n  if (isString2(value)) {\n    value.toUpperCase(); // ok\n  }\n}",
        "options": [
            ("A", "isString2 is generic, so the compiler can infer the argument type", False,
             "Neither function is generic. The difference is entirely in the declared return type."),
            ("B", "isString2 runs at compile time while isString1 runs at runtime", False,
             "Both run only at runtime. Type predicates are erased in the emitted JavaScript."),
            ("C", "val is string is a type predicate: it tells the compiler what a true return means about the argument", True,
             "Correct. boolean only says 'a boolean came back'. val is string says 'if this is true, val is a string', which control flow analysis can act on."),
            ("D", "isString1 needs an explicit return type annotation to narrow", False,
             "It has one — boolean. That is precisely the annotation that throws the information away."),
        ],
        "explanation": "A predicate return type (val is string) carries information the compiler can use; a plain boolean does not. When isString1 returns true, all TypeScript knows is that some boolean was true — it cannot connect that to the argument, so value stays string | number. isString2 declares the connection explicitly, so inside the if branch control flow analysis narrows value to string.",
        "interviewLine": "boolean loses the information; a type predicate keeps it. The runtime behaviour is identical — only the compiler can tell the difference.",
        "misconception": "Believing the compiler can infer a type guard from the function body. It will not; you must declare the predicate.",
        "hints": ["What does the compiler actually learn from a function that returns boolean?"],
        "minutes": 2,
    },
    {
        "id": "typescript-infer-conditional-unwrap",
        "title": "How infer captures a type inside a conditional type",
        "prompt": "What does UnpackPromise<T> resolve to for each of these two inputs?",
        "subject": "generics",
        "tags": ["typescript", "conditional-types", "infer", "generics", "senior"],
        "codeSnippet": "type UnpackPromise<T> = T extends Promise<infer U> ? U : T;\n\ntype A = UnpackPromise<Promise<string>>;\ntype B = UnpackPromise<number>;",
        "options": [
            ("A", "A = string, B = number", True,
             "Correct. T matches Promise<string> so U is captured as string; number does not match, so the false branch returns T unchanged."),
            ("B", "A = Promise<string>, B = number", False,
             "The whole point of infer U is to extract the inner type, not to return the Promise itself."),
            ("C", "A = string, B = never", False,
             "The false branch is T, not never. B falls through to the original type."),
            ("D", "A = unknown, B = unknown", False,
             "infer produces a concrete inferred type, not unknown."),
        ],
        "explanation": "infer introduces a type variable that TypeScript solves for while checking the extends clause. T extends Promise<infer U> asks 'is T some Promise, and if so what is it a Promise of?' — binding that answer to U. For Promise<string>, U becomes string and the true branch returns it. For number the check fails and the false branch returns T unchanged. infer is only legal inside the extends clause of a conditional type.",
        "interviewLine": "infer is pattern matching for types — it destructures a type the way you'd destructure a value.",
        "misconception": "Trying to use infer outside a conditional type's extends clause; it is only valid there.",
        "hints": ["What happens on the branch where the extends check fails?"],
        "minutes": 3,
    },
    {
        "id": "typescript-never-return-unreachable",
        "title": "The return type of a function that always throws",
        "prompt": "What return type does TypeScript infer for fail, and what does that buy you at the call site?",
        "subject": "types",
        "tags": ["typescript", "never", "control-flow", "senior"],
        "codeSnippet": "function fail(message: string) {\n  throw new Error(message);\n}\n\nfunction pick(value: string | null) {\n  if (value === null) fail('missing');\n  return value.toUpperCase();\n}",
        "options": [
            ("A", "void — the function returns nothing useful", False,
             "void would mean the function can return undefined normally. This one never returns at all, and void would leave the code after the call reachable."),
            ("B", "unknown — the compiler cannot tell", False,
             "The compiler can tell precisely: there is no reachable return path."),
            ("C", "Error — it is inferred from the thrown value", False,
             "The thrown value's type is unrelated to the return type; throwing is not returning."),
            ("D", "never — so the compiler treats code after the call as unreachable", True,
             "Correct. never means this function does not return, which lets control flow analysis narrow value to string after the guard."),
        ],
        "explanation": "Because fail unconditionally throws and has no reachable return statement, TypeScript infers never. That is the type of a value that cannot exist, and it drives control flow analysis: the compiler treats anything following a never-returning call as unreachable. In pick, that means the null case has already exited, so value is narrowed to string. void would be wrong — it says the function returns, just without a useful value.",
        "interviewLine": "never is the type of 'this never comes back' — it's what makes assertion helpers and exhaustiveness checks work.",
        "misconception": "Reaching for void when you mean never. void returns; never does not.",
        "hints": ["Is there any path through this function that reaches a return?"],
        "minutes": 2,
    },
    {
        "id": "typescript-isolated-modules-constraint",
        "title": "What --isolatedModules actually enforces",
        "prompt": "What constraint does the --isolatedModules compiler option place on each file?",
        "subject": "types",
        "tags": ["typescript", "tsconfig", "modules", "build", "senior"],
        "codeSnippet": None,
        "options": [
            ("A", "Every file must be independently transpilable, without cross-file type information", True,
             "Correct. It is a compatibility guarantee for single-file transpilers such as Babel, SWC and esbuild."),
            ("B", "Every module must be imported at most once across the program", False,
             "It says nothing about how often a module is imported."),
            ("C", "Circular imports between modules become compile errors", False,
             "Circular imports are unaffected by this flag."),
            ("D", "Each file is compiled into a separate output bundle", False,
             "It constrains what you may write; it does not change bundling or output layout."),
        ],
        "explanation": "--isolatedModules guarantees each file can be transpiled on its own, with no knowledge of any other file. That matters because Babel, SWC and esbuild transpile file-by-file and never build a full TypeScript program. It is why re-exporting a type needs export type { T }, why const enum is disallowed, and why every file must actually be a module. Next.js and Vite set it for exactly this reason.",
        "interviewLine": "isolatedModules is a promise to single-file transpilers: nothing in this file needs cross-file type information to compile.",
        "misconception": "Reading it as a bundling or module-resolution flag. It constrains the syntax you may write, not how output is produced.",
        "hints": ["Which tools compile one file at a time without type-checking the whole program?"],
        "minutes": 2,
    },
    {
        "id": "typescript-mapped-type-key-remapping",
        "title": "Renaming keys with an as clause in a mapped type",
        "prompt": "What is PersonGetters?",
        "subject": "generics",
        "tags": ["typescript", "mapped-types", "template-literal-types", "senior"],
        "codeSnippet": "type Getters<T> = {\n  [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K];\n};\n\ninterface Person {\n  name: string;\n  age: number;\n}\n\ntype PersonGetters = Getters<Person>;",
        "options": [
            ("A", "{ name: () => string; age: () => number }", False,
             "That is what you get without the as clause — the keys would keep their original names."),
            ("B", "{ getName: () => string; getAge: () => number }", True,
             "Correct. The as clause remaps each key through a template literal type, and each value becomes a function returning the original property type."),
            ("C", "{ getName: string; getAge: number }", False,
             "The value type is () => T[K], a function returning the property type, not the property type itself."),
            ("D", "{ get: (key: keyof Person) => string | number }", False,
             "A mapped type produces one member per key, not a single lookup method."),
        ],
        "explanation": "Key remapping (TypeScript 4.1+) lets a mapped type rewrite each key via an as clause. Here `get${Capitalize<string & K>}` turns name into getName and age into getAge — string & K is needed because keyof T can include number and symbol, and template literal types need a string. The value type () => T[K] makes each member a getter returning the original property type.",
        "interviewLine": "The as clause in a mapped type renames keys; combine it with template literal types and you can generate whole APIs from a shape.",
        "misconception": "Forgetting string & K and hitting an error because keyof T is not assignable to string.",
        "hints": ["Read the as clause as 'and call this key ... instead'."],
        "minutes": 3,
    },
    {
        "id": "typescript-template-literal-union-distribution",
        "title": "How a template literal type distributes over a union",
        "prompt": "What is the parameter type of event?",
        "subject": "types",
        "tags": ["typescript", "template-literal-types", "unions", "senior"],
        "codeSnippet": "type EventType = 'click' | 'focus' | 'blur';\ntype Handler = (event: `on${Capitalize<EventType>}`) => void;\n\nconst handler: Handler = (event) => {\n  console.log(event);\n};",
        "options": [
            ("A", "string", False,
             "Template literal types produce specific string literal types, not the widened string."),
            ("B", "'onclick' | 'onfocus' | 'onblur'", False,
             "Capitalize uppercases the first character of each member, so the c, f and b are capitalised."),
            ("C", "'onClick' | 'onFocus' | 'onBlur'", True,
             "Correct. The template distributes over each union member and Capitalize uppercases the first letter."),
            ("D", "`on${string}`", False,
             "The union members are known, so the result is a concrete union rather than an open pattern."),
        ],
        "explanation": "A template literal type distributes over any union it interpolates: each member of EventType is substituted in turn, producing a union of the results. Capitalize is one of TypeScript's built-in intrinsic string types, so 'click' becomes 'Click' and the whole thing becomes 'onClick'. The result is a closed union of three exact string literals, which is what lets the compiler autocomplete and reject typos.",
        "interviewLine": "Template literal types distribute over unions — one input union of three gives you an output union of three.",
        "misconception": "Expecting a single widened string. The union is preserved through the template.",
        "hints": ["What happens to each member of the union separately?"],
        "minutes": 2,
    },
    {
        "id": "typescript-recursive-deep-readonly",
        "title": "Why a deep-readonly type needs a conditional check",
        "prompt": "In DeepReadonly, why is the T[K] extends object check necessary?",
        "subject": "generics",
        "tags": ["typescript", "recursive-types", "mapped-types", "senior"],
        "codeSnippet": "type DeepReadonly<T> = {\n  readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K];\n};\n\ninterface Config {\n  api: { url: string; timeout: number };\n  features: string[];\n}\n\ntype ReadonlyConfig = DeepReadonly<Config>;",
        "options": [
            ("A", "It stops the recursion at primitives, which have no properties to map over", True,
             "Correct. Without it the type would try to recurse into string and number, which is meaningless and produces a useless mapped type."),
            ("B", "It prevents infinite recursion on any input", False,
             "It stops recursion at primitives, but a genuinely cyclic type can still recurse — TypeScript has its own depth limiter for that."),
            ("C", "It excludes arrays from being made readonly", False,
             "Arrays are objects, so they take the recursive branch and are made deeply readonly too."),
            ("D", "It is required syntax for any recursive type alias", False,
             "Recursive type aliases do not require a conditional; this one needs it for correctness, not syntax."),
        ],
        "explanation": "A mapped type applied to a primitive is not useful — mapping over keyof string gives you string's method names, not the value. The conditional check makes recursion stop at the leaves: object-shaped properties recurse, primitives are returned as-is. Arrays take the recursive branch because arrays are objects, which is usually what you want.",
        "interviewLine": "Recursive mapped types need a base case just like recursive functions — the conditional is that base case.",
        "misconception": "Assuming the conditional is about cycle-breaking. It is about not recursing into primitives.",
        "hints": ["What would DeepReadonly<string> mean?"],
        "minutes": 3,
    },
    {
        "id": "typescript-interface-declaration-merging",
        "title": "Declaration merging, and why type aliases cannot do it",
        "prompt": "Why does redeclaring Box compile while redeclaring Container is an error?",
        "subject": "types",
        "tags": ["typescript", "interfaces", "declaration-merging", "senior"],
        "codeSnippet": "interface Box { width: number }\ninterface Box { height: number }\nconst box: Box = { width: 10, height: 20 }; // ok\n\ntype Container = { volume: number };\ntype Container = { weight: number }; // error",
        "options": [
            ("A", "Interfaces are hoisted while type aliases are not", False,
             "Both are erased at runtime and both are usable before their declaration. Hoisting is not the difference."),
            ("B", "Interfaces merge their declarations into one; a type alias binds a name exactly once", True,
             "Correct. Declaration merging is a feature of interfaces specifically, which is what makes them extensible from other files."),
            ("C", "Type aliases can only describe primitives and unions", False,
             "Type aliases describe object shapes perfectly well — they simply cannot be declared twice."),
            ("D", "Box compiles only because both declarations are in the same file", False,
             "Merging works across files too, which is exactly how ambient library augmentation works."),
        ],
        "explanation": "Interfaces support declaration merging: multiple declarations of the same interface name combine into one, with properties unioned and identically-named methods becoming overloads. A type alias binds a name to exactly one type, so a second declaration is a redefinition error. Merging is why you augment third-party types by re-declaring their interface, and a good reason to prefer interface for public shapes you expect others to extend.",
        "interviewLine": "Interfaces are open — anyone can reopen and extend them. Type aliases are closed. That's the practical difference, not the syntax.",
        "misconception": "Treating interface and type as pure synonyms. Only interfaces merge, which matters for library augmentation.",
        "hints": ["How would you add a property to a type declared in someone else's package?"],
        "minutes": 2,
    },
    {
        "id": "typescript-variance-annotations-in-out",
        "title": "What the in and out variance annotations declare",
        "prompt": "What do the in and out modifiers on these type parameters mean?",
        "subject": "generics",
        "tags": ["typescript", "variance", "generics", "senior"],
        "codeSnippet": "interface Producer<out T> {\n  get(): T;\n}\n\ninterface Consumer<in T> {\n  set(value: T): void;\n}\n\ninterface Processor<in out T> {\n  process(value: T): T;\n}",
        "options": [
            ("A", "They mark parameters as input-only or output-only for the runtime", False,
             "They are erased at compile time and have no runtime meaning whatsoever."),
            ("B", "They restrict T to primitive types in the in case and object types in the out case", False,
             "They say nothing about what T may be — only about how the generic type relates under assignment."),
            ("C", "They declare variance explicitly: out is covariant, in is contravariant, in out is invariant", True,
             "Correct. They state the subtyping relationship the compiler would otherwise infer structurally."),
            ("D", "They make the type parameter optional at the use site", False,
             "Optionality of type arguments comes from defaults such as <T = string>, not from variance annotations."),
        ],
        "explanation": "Variance annotations (TypeScript 4.7+) declare how a generic type's assignability follows its type argument. out T is covariant: T appears only in output positions, so Producer<Dog> is assignable to Producer<Animal>. in T is contravariant: T appears only in input positions, so Consumer<Animal> is assignable to Consumer<Dog>. in out is invariant — neither direction is safe. TypeScript normally infers this structurally; annotating it makes the intent explicit, catches mistakes at the declaration, and speeds up checking of large generic types.",
        "interviewLine": "out means you only ever get T out, so widening is safe; in means you only ever put T in, so narrowing is safe.",
        "misconception": "Assuming variance annotations change what T can be. They only describe assignability between instantiations.",
        "hints": ["If you only ever read a T out of something, is it safe to treat it as producing a supertype?"],
        "minutes": 3,
    },
    {
        "id": "typescript-overload-implementation-signature",
        "title": "What an implementation signature must satisfy",
        "prompt": "A function has two overloads: (a: string) and (a: string, ...rest: number[]). What must be true of the implementation signature?",
        "subject": "types",
        "tags": ["typescript", "overloads", "functions", "senior"],
        "codeSnippet": "function format(a: string): string;\nfunction format(a: string, ...rest: number[]): string;\nfunction format(a: string, ...rest: number[]): string {\n  return rest.length ? `${a}:${rest.join(',')}` : a;\n}",
        "options": [
            ("A", "It must be callable by every overload, so the rest parameter has to accept being empty", True,
             "Correct. The first overload passes no rest arguments, so rest must be satisfiable as an empty array."),
            ("B", "It must exactly match one of the declared overloads", False,
             "It must be compatible with all of them, which usually means it is broader than any single one."),
            ("C", "It becomes part of the public API alongside the overloads", False,
             "The implementation signature is not callable from outside — only the overload signatures are visible."),
            ("D", "Rest parameters are not permitted in an implementation signature", False,
             "They are permitted and common; a rest parameter is the usual way to absorb differing arities."),
        ],
        "explanation": "Overload signatures define the public API; the implementation signature is invisible to callers and only has to be compatible with all of them. A rest parameter naturally satisfies this because it accepts zero or more arguments — calls matching the first overload simply bind rest to []. This is also why an implementation signature is usually wider than any individual overload, and why widening it does not widen what callers may actually pass.",
        "interviewLine": "Overload signatures are the API; the implementation signature is plumbing that has to satisfy all of them and is never callable itself.",
        "misconception": "Expecting callers to be able to use the implementation signature. Only the declared overloads are visible.",
        "hints": ["What does rest bind to when the caller passes only one argument?"],
        "minutes": 2,
    },
]
