"""
Authored for the TypeScript interview topics that the bank did not cover:
interfaces vs type aliases head-to-head, classes and access modifiers,
generic constraints, the type-system utilities, and the promise combinators.

Deliberately does NOT repeat material already added from the DEV/CoderPad
sources — as const, infer, type predicates, declaration merging, variance,
mapped-type key remapping, template literal types, overloads, isolatedModules
and the basic DeepReadonly all already exist in the bank.
"""

SOURCE = "typescript-masterclass"
CATEGORY = "typescript"
LANG = "typescript"

QUESTIONS = [
    # ─────────────────────────────── interfaces vs type aliases
    {
        "id": "typescript-interface-vs-type-alias-capabilities",
        "title": "Interface or type alias: which can do what",
        "prompt": "Which capability belongs to interfaces but NOT to type aliases?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "interfaces", "type-aliases", "declaration-merging"],
        "codeSnippet": "interface User { name: string }\ninterface User { age: number }   // merges\n\ntype Point = { x: number };\n// type Point = { y: number };   // error: duplicate identifier",
        "options": [
            ("A", "Describing the shape of an object", False,
             "Both do this equally well; a type alias for an object literal is entirely idiomatic."),
            ("B", "Being reopened and merged by a later declaration of the same name", True,
             "Correct. Declaration merging is unique to interfaces, and it is what makes global and module augmentation possible."),
            ("C", "Being used as the type of a function parameter", False,
             "Both can annotate a parameter."),
            ("D", "Being extended to build a wider shape", False,
             "Interfaces use extends and type aliases use &, but both compose."),
        ],
        "explanation": "The practical difference is openness. An interface can be declared more than once and the compiler merges the declarations, which is how you add a property to Window or augment a third-party module's types. A type alias binds a name exactly once — a second declaration is a duplicate identifier error. Everything else is largely symmetrical: both describe object shapes, both annotate parameters, both compose. Type aliases win where interfaces cannot go at all: unions, tuples, primitives and conditional types.",
        "interviewLine": "Interfaces are open, type aliases are closed. If someone else needs to extend it from another file, it has to be an interface.",
        "misconception": "Treating the two as pure synonyms. They differ precisely where extensibility matters.",
        "hints": ["What happens if you declare the same name twice with each?"],
        "minutes": 2,
    },
    {
        "id": "typescript-extends-vs-intersection-conflict",
        "title": "extends and & behave differently on a conflict",
        "prompt": "Both compose two shapes with a clashing member. What is the difference?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "intersection", "extends", "interfaces"],
        "codeSnippet": "interface A { id: string }\ninterface B extends A { id: number }      // (1)\n\ntype C = { id: string } & { id: number }; // (2)",
        "options": [
            ("A", "Both are errors — a member cannot be redeclared with a different type", False,
             "Only the interface form errors. The intersection is accepted at the declaration."),
            ("B", "(1) errors immediately; (2) is accepted but id becomes never, so it is unusable", True,
             "Correct. extends checks compatibility eagerly; & silently intersects the members instead."),
            ("C", "(1) is accepted and B.id narrows to number; (2) errors", False,
             "extends will not let a subtype change a member to an incompatible type."),
            ("D", "Both are accepted and the last declaration wins", False,
             "Neither uses last-wins semantics."),
        ],
        "explanation": "extends is checked at the point of declaration: an interface that extends another must remain assignable to it, so redeclaring id as an incompatible type is an error you see immediately. An intersection performs no such check — it intersects each member, and string & number has no inhabitants, so id becomes never. The type is accepted and the failure surfaces much later, wherever someone tries to assign to it. That earlier feedback is a real argument for extends when you are modelling inheritance.",
        "interviewLine": "extends fails at the declaration; & fails at the usage, with a never you have to go looking for.",
        "misconception": "Assuming & and extends are interchangeable. They differ exactly when members conflict.",
        "hints": ["What is the type string & number?"],
        "minutes": 3,
    },
    {
        "id": "typescript-union-requires-type-alias",
        "title": "What only a type alias can express",
        "prompt": "You need Status to be exactly 'idle' | 'loading' | 'done'. Which declaration works?",
        "level": "junior", "type": "concept", "subject": "types",
        "tags": ["typescript", "unions", "type-aliases", "interfaces"],
        "codeSnippet": "type Status = 'idle' | 'loading' | 'done';",
        "options": [
            ("A", "type Status = 'idle' | 'loading' | 'done'", True,
             "Correct. A union is not an object shape, so only a type alias can name it."),
            ("B", "interface Status { value: 'idle' | 'loading' | 'done' }", False,
             "That declares an object with a property, not the union itself."),
            ("C", "interface Status extends 'idle' | 'loading' | 'done' {}", False,
             "An interface can only extend an object type or a statically known shape, not a union of literals."),
            ("D", "Either — interfaces and type aliases both express unions", False,
             "Interfaces describe object shapes only. Unions, tuples and primitives need an alias."),
        ],
        "explanation": "An interface describes the shape of an object: a set of members. A union is not a shape — it is a choice between types — so there is nothing for an interface to declare. Type aliases have no such restriction: they name any type at all, including unions, tuples, primitives, conditional types and mapped types. This is the counterweight to declaration merging, and in practice it decides most real choices between the two.",
        "interviewLine": "Interfaces describe object shapes; aliases name any type. A union isn't a shape, so it has to be an alias.",
        "misconception": "Reaching for an interface by default and then wrapping the union in a pointless property.",
        "hints": ["Is a union a set of members, or a choice between types?"],
        "minutes": 2,
    },
    {
        "id": "typescript-module-augmentation-third-party",
        "title": "Adding a property to a third-party type",
        "prompt": "A library exports interface Config. You need to add a custom field to it from your own code. How?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "declaration-merging", "module-augmentation", "interfaces"],
        "codeSnippet": "declare module \"some-lib\" {\n  interface Config {\n    myFeatureFlag?: boolean;\n  }\n}",
        "options": [
            ("A", "Declare a type alias with the same name in your own file", False,
             "A type alias cannot merge — a duplicate name is an error, and it would not affect the library's type anyway."),
            ("B", "Reopen the interface inside declare module for that package, so the declarations merge", True,
             "Correct. Module augmentation is exactly this: declaration merging targeted at another package's types."),
            ("C", "Fork the package's .d.ts file and edit it in place", False,
             "It works until the next upgrade silently reverts it. Augmentation is the supported route."),
            ("D", "Cast every usage to any at the call sites that need the field", False,
             "That disables checking at each site instead of extending the type once."),
        ],
        "explanation": "Module augmentation reopens a declaration inside another package's module and merges into it. Because interfaces merge and type aliases do not, this only works if the library declared the shape as an interface — a real argument for exporting public shapes as interfaces in library code. The same mechanism extends global types: declare global { interface Window { myApp: App } }. Note that augmenting a module requires your file to be a module itself, so it needs at least one import or export.",
        "interviewLine": "Augmentation is declaration merging pointed at somebody else's package — which is exactly why library authors should export interfaces, not aliases.",
        "misconception": "Trying to augment with a type alias, or editing node_modules and losing it on the next install.",
        "hints": ["Which of the two declaration forms can be reopened?"],
        "minutes": 3,
    },

    # ─────────────────────────────── classes
    {
        "id": "typescript-access-modifiers-visibility",
        "title": "public, private and protected",
        "prompt": "Which statement about TypeScript's access modifiers is correct?",
        "level": "junior", "type": "concept", "subject": "types",
        "tags": ["typescript", "classes", "encapsulation", "access-modifiers"],
        "codeSnippet": "class Base {\n  public id = 1;      // everywhere\n  protected kind = \"b\"; // this class and subclasses\n  private secret = 42;  // this class only\n}\n\nclass Derived extends Base {\n  read() {\n    return this.kind;   // ok\n    // return this.secret; // error\n  }\n}",
        "options": [
            ("A", "protected members are visible to subclasses; private members are not", True,
             "Correct. That is the entire distinction between them."),
            ("B", "private members are visible to subclasses but not to outside callers", False,
             "That describes protected. private is limited to the declaring class."),
            ("C", "Members are private unless marked otherwise", False,
             "The default is public."),
            ("D", "protected members are accessible from any code in the same module", False,
             "Visibility follows the class hierarchy, not the file or module."),
        ],
        "explanation": "public is the default and imposes no restriction. protected narrows access to the declaring class and anything that extends it, which is what lets a base class expose internals to its subclasses without exposing them to consumers. private narrows further, to the declaring class alone — even a subclass cannot see it. All three are compile-time only and are erased from the emitted JavaScript, so none of them prevents access at runtime.",
        "interviewLine": "protected is for your subclasses, private is for you alone — and both are erased, so neither stops anyone at runtime.",
        "misconception": "Expecting a subclass to reach a private member. Only protected crosses the inheritance boundary.",
        "hints": ["Which one is about the inheritance chain rather than the class itself?"],
        "minutes": 2,
    },
    {
        "id": "typescript-private-keyword-vs-hash-private",
        "title": "private versus #private",
        "prompt": "What is the practical difference between private balance and #balance?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "classes", "encapsulation", "private-fields"],
        "codeSnippet": "class A {\n  private balance = 0;\n}\nclass B {\n  #balance = 0;\n}\n\nconsole.log((new A() as any).balance); // 0  — erased, still there\nconsole.log((new B() as any).balance); // undefined — genuinely hidden",
        "options": [
            ("A", "They are identical; # is only newer syntax for the same thing", False,
             "They enforce at different times — one at compile time, the other at runtime."),
            ("B", "private is a compile-time check that is erased; #balance is enforced by the runtime", True,
             "Correct. A cast to any defeats private; nothing defeats a # field."),
            ("C", "#balance is a TypeScript feature that compiles down to private", False,
             "# private fields are standard ECMAScript, not a TypeScript invention."),
            ("D", "private works on methods while # works only on fields", False,
             "Both apply to fields and methods."),
        ],
        "explanation": "private is part of the type system and vanishes with the types, so the property is still an ordinary property at runtime — a cast to any or a bracket access reaches it, and it shows up in JSON.stringify and Object.keys. A # field is real ECMAScript private state: the name is not a property key at all, access from outside is a syntax error, and it stays out of serialisation. Use private when you want the compiler to guide callers; use # when the boundary genuinely has to hold.",
        "interviewLine": "private is advice to the compiler; # is enforced by the engine. If untrusted code runs in your process, only one of them is real.",
        "misconception": "Assuming TypeScript's private survives compilation. It is erased along with every other annotation.",
        "hints": ["What is left in the emitted JavaScript for each?"],
        "minutes": 3,
    },
    {
        "id": "typescript-parameter-properties-shorthand",
        "title": "Parameter properties",
        "prompt": "What does the modifier on a constructor parameter do?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "classes", "constructor", "parameter-properties"],
        "codeSnippet": "class Point {\n  constructor(\n    public readonly x: number,\n    public readonly y: number,\n  ) {}\n}\n\n// equivalent to declaring both fields and assigning them in the body",
        "options": [
            ("A", "It declares a field and assigns the argument to it automatically", True,
             "Correct. An access modifier or readonly on a constructor parameter promotes it to a property."),
            ("B", "It marks the parameter optional at the call site", False,
             "Optionality comes from ? or a default value, not from an access modifier."),
            ("C", "It makes the parameter available to subclasses only", False,
             "Visibility follows whichever modifier you wrote; the promotion itself is the feature."),
            ("D", "It has no runtime effect and is purely documentation", False,
             "It emits a real assignment in the constructor."),
        ],
        "explanation": "Adding public, private, protected or readonly to a constructor parameter tells TypeScript to declare a field of the same name and assign the argument to it, replacing the usual declare-then-assign boilerplate. It is one of the few TypeScript features that emits code rather than being erased. Worth knowing the caveat: a parameter with no modifier stays an ordinary parameter, so mixing the two forms in one constructor is a common source of confusion.",
        "interviewLine": "A modifier on a constructor parameter promotes it to a field. It's one of the rare bits of TypeScript syntax that actually emits code.",
        "misconception": "Expecting every constructor parameter to become a property. Only the ones carrying a modifier do.",
        "hints": ["Compare it with writing the field declaration and the this.x = x line yourself."],
        "minutes": 2,
    },
    {
        "id": "typescript-implements-vs-extends",
        "title": "implements versus extends",
        "prompt": "What is the difference between a class that implements an interface and one that extends a base class?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "classes", "interfaces", "inheritance"],
        "codeSnippet": "interface Serializable { serialize(): string }\n\nclass Base { protected id = 0 }\n\nclass Doc extends Base implements Serializable {\n  serialize() { return String(this.id); }\n}",
        "options": [
            ("A", "implements copies the interface's members into the class", False,
             "It inherits nothing. The class must supply every member itself."),
            ("B", "implements is a compile-time conformance check that inherits no implementation; extends inherits real members", True,
             "Correct — which is also why a class may implement many interfaces but extend only one class."),
            ("C", "They are interchangeable; implements is preferred stylistically", False,
             "They do different jobs. Only extends brings behaviour."),
            ("D", "extends is erased at compile time while implements emits a prototype link", False,
             "This inverts it: extends emits the prototype chain, implements is erased."),
        ],
        "explanation": "implements asks the compiler to verify that a class satisfies a contract; it brings nothing with it, so every member has to be written out, and it disappears entirely from the emitted JavaScript. extends creates a real prototype chain and inherits implementations, which is why a class can implement any number of interfaces but extend exactly one class. Because TypeScript is structurally typed, a class that happens to have the right shape is assignable to the interface anyway — implements just makes the intent explicit and moves the error to the class rather than the call site.",
        "interviewLine": "implements is a checked promise; extends is actual inheritance. Structural typing means you don't need the promise — but you want the error where the class is, not where it's used.",
        "misconception": "Expecting implements to provide members. It only verifies that you wrote them.",
        "hints": ["Which one is still present in the compiled JavaScript?"],
        "minutes": 2,
    },
    {
        "id": "typescript-abstract-class-vs-interface",
        "title": "Abstract class or interface",
        "prompt": "When should you reach for an abstract class rather than an interface?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "classes", "abstract", "interfaces", "design"],
        "codeSnippet": "abstract class Repository<T> {\n  abstract find(id: string): Promise<T | null>;\n\n  // shared implementation subclasses inherit\n  async findOrFail(id: string): Promise<T> {\n    const found = await this.find(id);\n    if (!found) throw new Error(`not found: ${id}`);\n    return found;\n  }\n}",
        "options": [
            ("A", "When you need shared implementation alongside the contract", True,
             "Correct. An abstract class can ship working methods; an interface cannot ship any."),
            ("B", "When the contract must be satisfied by more than one class", False,
             "Interfaces handle that fine, and without consuming the single extends slot."),
            ("C", "When you want the contract checked at compile time", False,
             "Both are checked at compile time."),
            ("D", "When the type includes optional members", False,
             "Both express optional members with ?."),
        ],
        "explanation": "Both declare a contract, but only an abstract class can also provide implementation — concrete methods, constructor logic, protected state — while leaving some members abstract for subclasses to fill in. The cost is the single extends slot and a real runtime artifact. The rule of thumb: if you have behaviour to share, use an abstract class; if you only have a shape to describe, use an interface, which is free at runtime and can be implemented alongside anything else.",
        "interviewLine": "Interface when you have a shape; abstract class when you also have behaviour worth inheriting — and remember it spends the one extends slot.",
        "misconception": "Reaching for an abstract class purely to declare a contract, and paying the inheritance cost for nothing.",
        "hints": ["Which of the two can contain a method with a body?"],
        "minutes": 3,
    },

    # ─────────────────────────────── generics
    {
        "id": "typescript-generic-constraint-extends",
        "title": "Constraining a type parameter",
        "prompt": "Why does the unconstrained version fail to compile?",
        "level": "intermediate", "type": "concept", "subject": "generics",
        "tags": ["typescript", "generics", "constraints", "keyof"],
        "codeSnippet": "function longest1<T>(a: T, b: T) {\n  return a.length >= b.length ? a : b; // error: no 'length' on T\n}\n\nfunction longest2<T extends { length: number }>(a: T, b: T) {\n  return a.length >= b.length ? a : b; // ok\n}",
        "options": [
            ("A", "An unconstrained T could be anything, so the compiler cannot assume it has length", True,
             "Correct. extends narrows what T may be, which is what unlocks the member access."),
            ("B", "Generic functions cannot access properties of their parameters at all", False,
             "They can, once the constraint guarantees the property exists."),
            ("C", "T must be constrained to a class for property access to work", False,
             "Any constraint that guarantees the member is enough — an object literal type works."),
            ("D", "The two parameters must have different type parameters", False,
             "Sharing T is correct here and is not the cause of the error."),
        ],
        "explanation": "An unconstrained type parameter stands for absolutely any type, so the compiler can only allow operations valid on every type — and .length is not one of them. extends { length: number } narrows the set of acceptable types and, in exchange, lets you use that member inside the body. This is the fundamental trade of generics: the more you constrain, the more you can do. The constraint also improves the call site, rejecting a number argument at the caller rather than deep inside the function.",
        "interviewLine": "A constraint is a two-way deal: you narrow what callers may pass, and in return the compiler lets you use what you've guaranteed.",
        "misconception": "Reading extends as inheritance. On a type parameter it means 'is assignable to'.",
        "hints": ["What can you safely do to a value whose type could be anything at all?"],
        "minutes": 2,
    },
    {
        "id": "typescript-keyof-generic-property-lookup",
        "title": "Typing a property getter with keyof",
        "prompt": "What is the return type of getProperty(user, 'age')?",
        "level": "senior", "type": "concept", "subject": "generics",
        "tags": ["typescript", "generics", "keyof", "indexed-access"],
        "codeSnippet": "function getProperty<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst user = { name: \"Ada\", age: 36 };\nconst a = getProperty(user, \"age\");",
        "options": [
            ("A", "string | number — the union of the object's value types", False,
             "The indexed access type T[K] resolves to the specific member, not the union of all of them."),
            ("B", "number, because K is inferred as the literal 'age' and T['age'] is number", True,
             "Correct. K is inferred as a literal key, so the lookup resolves exactly."),
            ("C", "any, because the key is only known at runtime", False,
             "The key is a string literal, so it is known statically."),
            ("D", "unknown, because T is generic", False,
             "T is inferred from the argument as the concrete object type."),
        ],
        "explanation": "Two inferences make this work. T is inferred from obj as { name: string; age: number }, and K is inferred from the literal argument as 'age' rather than widening to string — because K is constrained to keyof T, which is a union of literal types. T[K] is then an indexed access type resolving to number. The same signature also rejects getProperty(user, 'email') at compile time, since 'email' is not in keyof T.",
        "interviewLine": "keyof plus an indexed access type turns a runtime lookup into a compile-time one — the return type follows the key you actually passed.",
        "misconception": "Expecting the union of all property types. The literal key resolves to exactly one.",
        "hints": ["What does K infer as when the argument is a string literal constrained to keyof T?"],
        "minutes": 3,
    },
    {
        "id": "typescript-generic-default-type-parameter",
        "title": "Default type parameters",
        "prompt": "What does the = Record<string, unknown> do here?",
        "level": "intermediate", "type": "concept", "subject": "generics",
        "tags": ["typescript", "generics", "defaults"],
        "codeSnippet": "interface ApiResponse<T = Record<string, unknown>> {\n  data: T;\n  status: number;\n}\n\nconst a: ApiResponse = { data: {}, status: 200 };\nconst b: ApiResponse<User[]> = { data: users, status: 200 };",
        "options": [
            ("A", "It constrains T so only Record<string, unknown> may be passed", False,
             "That is what extends does. = supplies a fallback and constrains nothing."),
            ("B", "It supplies the type argument when the caller omits one", True,
             "Correct — the same idea as a default parameter value, at the type level."),
            ("C", "It makes T optional at runtime", False,
             "Type parameters have no runtime existence at all."),
            ("D", "It forces T to be inferred rather than written explicitly", False,
             "Explicit type arguments remain available, as ApiResponse<User[]> shows."),
        ],
        "explanation": "A default type argument lets a generic be used without type arguments, which keeps common cases terse while leaving the parameter available when you need it. It is orthogonal to a constraint, and the two combine: <T extends object = Record<string, unknown>> both restricts what may be passed and supplies a fallback. As with value parameters, defaults must come after any non-defaulted parameters.",
        "interviewLine": "extends restricts what T may be; = says what T is when nobody specifies. They're independent and often used together.",
        "misconception": "Confusing = with extends. One is a fallback, the other a restriction.",
        "hints": ["What is the analogous feature for ordinary function parameters?"],
        "minutes": 2,
    },
    {
        "id": "typescript-deep-readonly-builtin-objects",
        "title": "Where a naive DeepReadonly breaks down",
        "prompt": "DeepReadonly<T> recurses whenever a property extends object. What does that do to a Date or a Map?",
        "level": "senior", "type": "concept", "subject": "generics",
        "tags": ["typescript", "recursive-types", "mapped-types", "built-ins"],
        "codeSnippet": "type DeepReadonly<T> = {\n  readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K];\n};\n\ninterface State {\n  updatedAt: Date;\n  index: Map<string, number>;\n}\n\ntype Frozen = DeepReadonly<State>;",
        "options": [
            ("A", "They are left untouched, because built-in types are excluded automatically", False,
             "There is no exclusion. Date and Map both satisfy extends object."),
            ("B", "The compiler errors, because a mapped type cannot be applied to a built-in", False,
             "It compiles happily. The problem is what it produces."),
            ("C", "They are mapped over as plain objects, producing a readonly bag of their method signatures rather than a usable Date or Map", True,
             "Correct. You get something shaped like the methods, and the mutating ones are still there — readonly on a method property prevents reassigning it, not calling it."),
            ("D", "They become never, since their internal state is not enumerable", False,
             "They do not become never; they become a mapped shape over their public members."),
        ],
        "explanation": "Date and Map both satisfy extends object, so the recursion maps over their members. What comes back is a readonly object with the same method signatures — not a Date you can pass to anything expecting one, and no protection at all, because readonly stops you reassigning index.set, not calling it. A production-grade version has to special-case built-ins, typically by short-circuiting on known types before the object check and treating readonly collections as ReadonlyMap or ReadonlySet. Deep recursion also runs into the compiler's instantiation depth limit on large types.",
        "interviewLine": "extends object catches Date, Map and RegExp too — you get a readonly bag of method signatures, which is type-safety theatre rather than immutability.",
        "misconception": "Believing a one-line DeepReadonly is production-ready. It is correct only for plain data.",
        "hints": ["Does readonly on a property that holds a method prevent calling that method?"],
        "minutes": 3,
    },

    # ─────────────────────────────── the type system
    {
        "id": "typescript-unknown-vs-any-boundary",
        "title": "unknown versus any at a data boundary",
        "prompt": "An API response arrives untyped. Why is unknown the better annotation?",
        "level": "intermediate", "type": "concept", "subject": "narrowing",
        "tags": ["typescript", "unknown", "any", "type-safety", "narrowing"],
        "codeSnippet": "const a: any = await res.json();\na.user.name.toUpperCase();     // compiles. may explode at runtime.\n\nconst b: unknown = await res.json();\n// b.user;                     // error until you prove the shape\nif (isUser(b)) b.name.toUpperCase();",
        "options": [
            ("A", "unknown is faster because it skips runtime checks", False,
             "Neither performs runtime checks; both are erased."),
            ("B", "unknown forces you to narrow before using the value; any silently disables checking and spreads", True,
             "Correct. any leaks outward through every expression it touches."),
            ("C", "unknown allows every operation that any allows, with better error messages", False,
             "unknown allows almost no operations until narrowed. That is the point."),
            ("D", "any is disallowed under strict, so unknown is the only option", False,
             "strict does not forbid any."),
        ],
        "explanation": "any switches the type system off for a value and for everything derived from it — read a property off an any and the result is any too, so a single annotation at the boundary can hollow out an entire module. unknown accepts anything on the way in but permits almost nothing on the way out until you narrow it with a type guard, a typeof check or a schema validator. That makes it the right type for anything crossing a trust boundary: fetch responses, JSON.parse, postMessage payloads, third-party callbacks.",
        "interviewLine": "any is an opt-out that spreads; unknown is an opt-in that stops. At a trust boundary you want the one that forces a check.",
        "misconception": "Treating any as 'unknown but more convenient'. It is the absence of typing, and it is contagious.",
        "hints": ["What is the type of x.foo when x is any?"],
        "minutes": 2,
    },
    {
        "id": "typescript-satisfies-operator",
        "title": "What satisfies does that an annotation does not",
        "prompt": "Why use satisfies here instead of a type annotation?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "satisfies", "inference", "literal-types"],
        "codeSnippet": "type Routes = Record<string, { path: string; auth: boolean }>;\n\nconst routes = {\n  home: { path: \"/\", auth: false },\n  admin: { path: \"/admin\", auth: true },\n} satisfies Routes;\n\nroutes.home.path;   // ok — key is known\n// routes.missing;  // error — not a key\n\nconst annotated: Routes = { /* …same… */ };\nannotated.anything; // no error — widened to the index signature",
        "options": [
            ("A", "satisfies checks the value against the type but keeps the narrower inferred type", True,
             "Correct. You get the constraint checked without losing the specific keys and literal values."),
            ("B", "satisfies performs the check at runtime rather than compile time", False,
             "It is erased like every other type-level construct."),
            ("C", "satisfies is a shorthand for as, without the unsoundness", False,
             "as reinterprets a type; satisfies checks one and changes nothing about the inferred type."),
            ("D", "satisfies makes the object readonly, like as const", False,
             "It does not affect mutability. Combining it with as const is common precisely because they do different jobs."),
        ],
        "explanation": "An annotation widens the value to the annotated type: once routes is Routes, the compiler only knows it is a string-keyed record, so the specific keys are gone and typos on lookup go unnoticed. satisfies checks the value against the type and then throws the type away, leaving the narrow inferred type in place — so the keys stay known and the literal values stay literal, while still failing if a route is missing auth. It is the tool for 'conform to this contract but remember exactly what I wrote'.",
        "interviewLine": "An annotation replaces the inferred type; satisfies validates against it and keeps what you wrote.",
        "misconception": "Thinking satisfies is just a safer as. as reinterprets, satisfies verifies.",
        "hints": ["After annotating with Record<string, …>, does the compiler still know which keys exist?"],
        "minutes": 3,
    },
    {
        "id": "typescript-discriminated-union-exhaustive-never",
        "title": "Exhaustiveness checking with never",
        "prompt": "A new variant is added to the union but not to the switch. What does the never assignment do?",
        "level": "senior", "type": "concept", "subject": "narrowing",
        "tags": ["typescript", "discriminated-unions", "never", "exhaustiveness"],
        "codeSnippet": "type Shape =\n  | { kind: \"circle\"; r: number }\n  | { kind: \"square\"; size: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case \"circle\": return Math.PI * s.r ** 2;\n    case \"square\": return s.size ** 2;\n    default: {\n      const exhaustive: never = s;\n      return exhaustive;\n    }\n  }\n}",
        "options": [
            ("A", "Nothing — the default branch is unreachable and is stripped", False,
             "It is reachable as far as the compiler is concerned the moment a variant is unhandled."),
            ("B", "It throws at runtime when an unknown shape arrives", False,
             "It is a compile-time device; nothing is thrown, and the annotation is erased."),
            ("C", "It fails to compile, because the unhandled variant is no longer assignable to never", True,
             "Correct. Adding a variant turns a silent omission into a build error at every switch."),
            ("D", "It widens s to unknown inside the default branch", False,
             "Narrowing works the other way: handled cases are removed from the union."),
        ],
        "explanation": "Inside the switch, each handled case is removed from the union, so by the default branch s has narrowed to never — the type with no values — and assigning never to never is fine. Add a third variant and the default branch now narrows to that variant instead, which is not assignable to never, so the build fails. That turns 'I forgot to handle a case' from a runtime surprise into a compile error at every exhaustive switch in the codebase, which is the main practical reason to use discriminated unions over loose objects.",
        "interviewLine": "The never assignment is a tripwire: add a variant and every switch that forgot it stops compiling.",
        "misconception": "Thinking the default branch is dead code. It is the assertion that keeps the union honest.",
        "hints": ["What has s narrowed to once every case has been handled?"],
        "minutes": 3,
    },
    {
        "id": "typescript-structural-typing-duck",
        "title": "Structural typing",
        "prompt": "Point was never mentioned when Named was declared. Does the assignment compile?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "structural-typing", "assignability"],
        "codeSnippet": "interface Named { name: string }\n\nclass Person {\n  constructor(public name: string, public age: number) {}\n}\n\nconst n: Named = new Person(\"Ada\", 36);",
        "options": [
            ("A", "No — Person must declare implements Named", False,
             "That would be required under nominal typing. TypeScript is structural."),
            ("B", "Yes — Person has a compatible name, and extra members are allowed on a non-literal value", True,
             "Correct. Compatibility is decided by shape, not by declared relationships."),
            ("C", "No — the extra age property makes it incompatible", False,
             "Extra properties are fine here; excess property checks only apply to fresh object literals."),
            ("D", "Only if Named is declared as a type alias rather than an interface", False,
             "Interfaces and aliases behave identically for assignability."),
        ],
        "explanation": "TypeScript compares types by structure, not by name: anything with a string name is assignable to Named, whether or not it ever heard of it. This is why implements is a convenience rather than a requirement, and why types from different libraries interoperate without adapters. Two caveats: a fresh object literal gets an excess property check, which rejects unexpected members; and private members make a class nominal in practice, since two classes with identically-named privates are still not assignable to each other.",
        "interviewLine": "TypeScript checks shape, not lineage. If it has the members, it's assignable — declared relationships are documentation.",
        "misconception": "Assuming a class must implement an interface to satisfy it. Structural typing says otherwise.",
        "hints": ["Does TypeScript care what the type is called, or what it contains?"],
        "minutes": 2,
    },
    {
        "id": "typescript-excess-property-check-literals",
        "title": "Why the literal errors but the variable does not",
        "prompt": "The same object is rejected in one form and accepted in the other. Why?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "excess-property-check", "assignability", "literals"],
        "codeSnippet": "interface Options { width: number }\n\n// const a: Options = { width: 10, height: 5 }; // error: 'height' does not exist\n\nconst raw = { width: 10, height: 5 };\nconst b: Options = raw; // ok",
        "options": [
            ("A", "raw is inferred as Options, so height is discarded", False,
             "raw is inferred as { width: number; height: number }; nothing is discarded."),
            ("B", "Object literals get an excess property check; a variable is only checked for structural compatibility", True,
             "Correct. The literal check is a deliberate extra guard against typos, and it applies only to fresh literals."),
            ("C", "The error is a bug that a type assertion works around", False,
             "It is intentional behaviour, not a bug."),
            ("D", "Interfaces reject extra properties while type aliases accept them", False,
             "Both behave identically. The difference is literal versus variable, not interface versus alias."),
        ],
        "explanation": "Structurally, { width: number; height: number } is assignable to Options — it has everything required. But TypeScript adds an excess property check for fresh object literals assigned directly to a typed target, because an unexpected member there is almost always a typo or a misremembered option name. Assign through a variable and the freshness is gone, so only ordinary structural compatibility applies. The right fix is usually to correct the property name, not to widen the target or reach for as.",
        "interviewLine": "Excess property checks only fire on fresh literals — it's a typo catcher, deliberately sitting on top of structural assignability.",
        "misconception": "Concluding the type system is inconsistent. The extra check exists exactly where typos happen.",
        "hints": ["What is different about a value written inline versus one that arrived in a variable?"],
        "minutes": 3,
    },
    {
        "id": "typescript-utility-types-pick-omit-partial",
        "title": "Choosing between Partial, Pick, Omit and Required",
        "prompt": "You need a type with every property of User optional. Which utility?",
        "level": "junior", "type": "concept", "subject": "types",
        "tags": ["typescript", "utility-types", "partial", "pick", "omit"],
        "codeSnippet": "interface User { id: string; name: string; email: string }\n\ntype Draft = Partial<User>;              // all optional\ntype Public = Omit<User, \"email\">;       // drop a key\ntype Creds = Pick<User, \"id\" | \"email\">; // keep only these\ntype Full = Required<Draft>;             // all required again",
        "options": [
            ("A", "Pick<User, keyof User>", False,
             "That reproduces User unchanged — Pick selects keys, it does not change optionality."),
            ("B", "Partial<User>", True,
             "Correct. Partial maps every property to optional; Required is its inverse."),
            ("C", "Omit<User, never>", False,
             "Omit removes keys. Removing none leaves the original type."),
            ("D", "Readonly<User>", False,
             "Readonly changes mutability, not optionality."),
        ],
        "explanation": "These four cover most day-to-day shape manipulation and are all one-line mapped types in lib.d.ts. Partial<T> makes every property optional and Required<T> reverses it; Readonly<T> is the mutability equivalent. Pick<T, K> keeps a subset of keys while Omit<T, K> drops one — Omit is the more maintainable of the pair for a public shape, since a newly added field is included by default rather than silently missing. Deriving these from one source interface is what keeps a create-DTO and an update-DTO from drifting apart.",
        "interviewLine": "Derive your DTOs from one interface with Pick, Omit and Partial. Hand-maintained parallel shapes drift; derived ones can't.",
        "misconception": "Confusing Pick and Omit with Partial. The first two select keys; Partial changes optionality.",
        "hints": ["Which of these touches optionality rather than the set of keys?"],
        "minutes": 2,
    },
    {
        "id": "typescript-returntype-parameters-awaited",
        "title": "Deriving types from a function you already have",
        "prompt": "getUser returns Promise<User>. What is Result?",
        "level": "senior", "type": "concept", "subject": "generics",
        "tags": ["typescript", "utility-types", "ReturnType", "Awaited", "infer"],
        "codeSnippet": "async function getUser(id: string, full: boolean) {\n  return { id, name: \"Ada\" };\n}\n\ntype Args = Parameters<typeof getUser>;          // [string, boolean]\ntype Raw = ReturnType<typeof getUser>;           // Promise<{ id: string; name: string }>\ntype Result = Awaited<ReturnType<typeof getUser>>;",
        "options": [
            ("A", "Promise<{ id: string; name: string }>", False,
             "That is ReturnType alone. Awaited is what unwraps the promise."),
            ("B", "{ id: string; name: string }", True,
             "Correct. Awaited<T> recursively unwraps promises, so the resolved value type comes out."),
            ("C", "unknown, because the return type is inferred rather than annotated", False,
             "An inferred return type is a real type and ReturnType reads it fine."),
            ("D", "[string, boolean], the parameter tuple", False,
             "That is Parameters, not ReturnType."),
        ],
        "explanation": "typeof getUser lifts the function value into the type world; ReturnType<F> then extracts its return type with a conditional type and infer, and Parameters<F> extracts the argument tuple. Awaited<T> unwraps a promise — recursively, so a nested Promise<Promise<T>> still resolves to T, and a non-promise passes through unchanged. Composing them means the derived types follow the implementation automatically instead of being restated and left to rot.",
        "interviewLine": "typeof lifts a value into the type world; ReturnType, Parameters and Awaited read it from there. Derive rather than restate.",
        "misconception": "Forgetting the Awaited step and ending up with a Promise where the resolved value was wanted.",
        "hints": ["An async function's return type is always what?"],
        "minutes": 3,
    },
    {
        "id": "typescript-record-vs-index-signature",
        "title": "Record versus an index signature",
        "prompt": "What is the practical difference between these two declarations?",
        "level": "intermediate", "type": "concept", "subject": "types",
        "tags": ["typescript", "record", "index-signature", "mapped-types"],
        "codeSnippet": "type A = { [key: string]: number };\ntype B = Record<string, number>;      // identical to A\n\ntype Role = \"admin\" | \"guest\";\ntype C = Record<Role, number>;        // { admin: number; guest: number }\n// type D = { [key: Role]: number };  // not expressible this way",
        "options": [
            ("A", "Record can key on a finite union to produce exactly those keys; an index signature cannot", True,
             "Correct. Over string they are equivalent, but Record<Role, …> gives a closed, required set of keys."),
            ("B", "Record allows any value type while an index signature only allows primitives", False,
             "Both accept any value type."),
            ("C", "Record is checked at runtime, an index signature is not", False,
             "Neither exists at runtime."),
            ("D", "An index signature makes properties optional; Record makes them required", False,
             "An index signature says nothing about which keys exist; Record over a union requires all of them."),
        ],
        "explanation": "Over an open key type they are the same thing — Record<string, V> is defined as a mapped type that produces exactly { [k: string]: V }. The difference appears with a finite key union: Record<Role, number> produces two named, required properties, so forgetting one is an error and adding a member to Role breaks every incomplete record. An index signature can never do that, because it describes an open set of keys rather than a specific one. Note that reading through an open index signature is unchecked unless noUncheckedIndexedAccess is on.",
        "interviewLine": "Record over a union gives you a closed, required key set — which is what turns adding an enum member into a compile error instead of a bug.",
        "misconception": "Treating Record<string, V> as safer than an index signature. They are the same; the win comes from a finite key type.",
        "hints": ["What happens if you pass a union of literals as the key type?"],
        "minutes": 3,
    },

    # ─────────────────────────────── promises
    {
        "id": "javascript-promise-all-fail-fast",
        "title": "What Promise.all does when one input rejects",
        "prompt": "One of the three requests rejects. What happens?",
        "level": "intermediate", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "promise-all", "async"],
        "codeSnippet": "const results = await Promise.all([\n  fetch(\"/a\"),\n  fetch(\"/b\"), // rejects\n  fetch(\"/c\"),\n]);",
        "options": [
            ("A", "The returned promise rejects immediately with that error, and the other results are lost", True,
             "Correct. Promise.all is fail-fast: one rejection settles the whole thing, and the successful values are unreachable."),
            ("B", "The array comes back with undefined in the failed position", False,
             "There is no partial array — the aggregate promise rejects instead of fulfilling."),
            ("C", "The other two requests are cancelled", False,
             "They keep running to completion. Promises have no cancellation."),
            ("D", "It waits for all three, then rejects with an array of errors", False,
             "That is closer to Promise.any's AggregateError. all rejects with the first error, as soon as it happens."),
        ],
        "explanation": "Promise.all fulfils with an array of values only if every input fulfils; the first rejection rejects the aggregate immediately with that reason. Two consequences catch people out. The successful results are simply gone — there is no way to reach them from the rejected promise. And the other operations are not cancelled: they run to completion in the background, so any side effects still happen and a later rejection among them can surface as an unhandled rejection.",
        "interviewLine": "all is fail-fast and all-or-nothing. It doesn't cancel the others, it just stops caring about them.",
        "misconception": "Expecting a partial array on failure. You get a rejection, not partial results.",
        "hints": ["Is there any way to reach the two successful values afterwards?"],
        "minutes": 2,
    },
    {
        "id": "javascript-promise-allsettled-result-shape",
        "title": "The shape Promise.allSettled returns",
        "prompt": "What does results look like when the second promise rejects?",
        "level": "intermediate", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "allSettled", "async"],
        "codeSnippet": "const results = await Promise.allSettled([\n  Promise.resolve(1),\n  Promise.reject(new Error(\"boom\")),\n]);",
        "options": [
            ("A", "[1, Error]", False,
             "The values are wrapped in descriptor objects rather than returned bare."),
            ("B", "It rejects with the error, like Promise.all", False,
             "allSettled never rejects because an input rejected."),
            ("C", "[{ status: \"fulfilled\", value: 1 }, { status: \"rejected\", reason: Error }]", True,
             "Correct. Every entry is a descriptor, and you branch on status."),
            ("D", "[1] — rejected entries are omitted", False,
             "Nothing is omitted; the array always has one entry per input, in order."),
        ],
        "explanation": "Promise.allSettled waits for every input to settle and always fulfils, with one descriptor per input in the original order. A fulfilled entry carries status: 'fulfilled' and value; a rejected entry carries status: 'rejected' and reason. Because it never rejects, it also means none of the inputs produce an unhandled rejection. That makes it the right tool when partial success is acceptable — fanning out to several independent services, or a batch where you want to report which items failed.",
        "interviewLine": "allSettled always fulfils and hands you a descriptor per input. Use it when partial success is a real outcome, not a failure.",
        "misconception": "Expecting bare values. Every entry is wrapped, so you must branch on status before reading value.",
        "hints": ["How would you tell success from failure if the values came back bare?"],
        "minutes": 2,
    },
    {
        "id": "javascript-promise-all-vs-allsettled-choice",
        "title": "Choosing between Promise.all and Promise.allSettled",
        "prompt": "A dashboard loads three independent widgets. One endpoint is flaky. Which combinator, and why?",
        "level": "senior", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "promise-all", "allSettled", "design"],
        "codeSnippet": "const [a, b, c] = await Promise.allSettled([loadA(), loadB(), loadC()]);\n\nrender({\n  a: a.status === \"fulfilled\" ? a.value : null,\n  b: b.status === \"fulfilled\" ? b.value : null,\n  c: c.status === \"fulfilled\" ? c.value : null,\n});",
        "options": [
            ("A", "Promise.all, because it is faster when everything succeeds", False,
             "Both await the same concurrent work. all is not faster; it just gives up earlier."),
            ("B", "Promise.all, so the whole dashboard fails atomically", False,
             "Atomic failure is right when the results are interdependent. Independent widgets are the opposite case."),
            ("C", "Promise.allSettled, so one flaky widget cannot blank the two that loaded fine", True,
             "Correct. The results are independent, so partial success is a legitimate outcome worth rendering."),
            ("D", "Promise.race, to return as soon as the fastest widget resolves", False,
             "race gives you one result and discards the rest — wrong shape for rendering three widgets."),
        ],
        "explanation": "The choice follows from whether the results are interdependent. If you need all three to proceed — say three parts of a single transaction — Promise.all is right, because a partial result is meaningless and failing fast is the honest outcome. If the results are independent, as with dashboard widgets, all throws away two perfectly good responses because a third failed. allSettled preserves them and lets each widget render its own error state. The performance is identical either way; both start all the work concurrently.",
        "interviewLine": "all when a partial result is meaningless; allSettled when it isn't. It's a question about your data, not about speed.",
        "misconception": "Reaching for Promise.all reflexively and turning one flaky dependency into a blank page.",
        "hints": ["Is a dashboard with two of three widgets loaded a useful screen, or a failure?"],
        "minutes": 3,
    },
    {
        "id": "javascript-promise-race-vs-any",
        "title": "Promise.race versus Promise.any",
        "prompt": "The first promise to settle rejects, and a later one fulfils. How do race and any differ?",
        "level": "senior", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "race", "any", "async"],
        "codeSnippet": "const fast = Promise.reject(new Error(\"fast failure\"));\nconst slow = new Promise((r) => setTimeout(() => r(\"ok\"), 100));\n\nawait Promise.race([fast, slow]); // ?\nawait Promise.any([fast, slow]);  // ?",
        "options": [
            ("A", "race rejects with the fast failure; any ignores it and fulfils with \"ok\"", True,
             "Correct. race settles on the first to settle either way; any waits for the first to fulfil."),
            ("B", "Both reject with the fast failure", False,
             "any only rejects if every input rejects."),
            ("C", "Both fulfil with \"ok\"", False,
             "race does not skip rejections — the first settlement wins whatever it is."),
            ("D", "race fulfils with \"ok\"; any rejects with an AggregateError", False,
             "This inverts both behaviours."),
        ],
        "explanation": "race settles as soon as any input settles, adopting that outcome whether it fulfilled or rejected — which is what makes it right for timeouts, where you deliberately want the timer's rejection to win. any is success-seeking: it ignores rejections and fulfils with the first value to arrive, rejecting only if every input rejects, and then with an AggregateError carrying all the reasons. Reach for race to bound how long you wait, and for any to take whichever redundant source answers first.",
        "interviewLine": "race takes the first settlement; any takes the first success. That's why race is the timeout tool and any is the redundancy tool.",
        "misconception": "Expecting race to skip a rejection and wait for a value. It adopts whatever settles first.",
        "hints": ["Which of the two can reject before every input has settled?"],
        "minutes": 3,
    },
    {
        "id": "javascript-promise-resolve-semantics",
        "title": "What Promise.resolve actually does",
        "prompt": "Which statement about Promise.resolve is correct?",
        "level": "intermediate", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "promise-resolve", "thenable"],
        "codeSnippet": "const p = Promise.resolve(42);\nPromise.resolve(p) === p;           // true — passed through\n\nconst thenable = { then: (res) => res(\"hi\") };\nawait Promise.resolve(thenable);   // \"hi\" — adopted",
        "options": [
            ("A", "It always allocates a new promise wrapping its argument", False,
             "Given a native promise it returns that same promise unchanged."),
            ("B", "It returns the argument unchanged if it is already a promise, adopts a thenable, and otherwise wraps the value", True,
             "Correct — which is what makes it the safe way to normalise a value of unknown promise-ness."),
            ("C", "It resolves the promise synchronously, so the value is available immediately", False,
             "The promise is already settled, but its callbacks still run in a microtask."),
            ("D", "It is identical to new Promise(res => res(value)) in every case", False,
             "That form always allocates and does not pass an existing promise through."),
        ],
        "explanation": "Promise.resolve normalises. Hand it a native promise and you get that exact promise back — no wrapping, no extra tick. Hand it a thenable, any object with a then method, and it adopts its eventual state, which is how interop with older promise libraries works. Hand it a plain value and you get an already-fulfilled promise. That is why it is the idiomatic way to accept 'a value or a promise of one', and why Promise.resolve().then(fn) is a common way to queue a microtask. Being settled does not make it synchronous — the callback still waits for the microtask queue.",
        "interviewLine": "Promise.resolve normalises rather than wraps — same promise back if it already was one, adopted if it's a thenable.",
        "misconception": "Assuming an already-resolved promise runs its .then synchronously. Settled still means a microtask.",
        "hints": ["What does it return when the argument is already a native promise?"],
        "minutes": 2,
    },
    {
        "id": "typescript-promise-all-tuple-inference",
        "title": "How TypeScript types the result of Promise.all",
        "prompt": "What is the type of the destructured results?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "promises", "tuples", "inference", "awaited"],
        "codeSnippet": "declare function getUser(): Promise<User>;\ndeclare function getPosts(): Promise<Post[]>;\ndeclare function getCount(): Promise<number>;\n\nconst [user, posts, count] = await Promise.all([\n  getUser(),\n  getPosts(),\n  getCount(),\n]);",
        "options": [
            ("A", "All three are (User | Post[] | number), so each needs narrowing", False,
             "That is what you would get from an array type. The overload preserves the tuple positions."),
            ("B", "user: User, posts: Post[], count: number — the tuple positions are preserved", True,
             "Correct. Promise.all is overloaded for tuples, and Awaited unwraps each element type."),
            ("C", "All three are unknown until asserted", False,
             "Nothing is lost; the types flow through."),
            ("D", "All three are Promise-wrapped and need a further await", False,
             "A single await unwraps the aggregate; the elements are already resolved values."),
        ],
        "explanation": "Promise.all is declared with an overload taking a readonly tuple, so passing an array literal of three differently-typed promises preserves the arity and the position of each. The signature maps Awaited over each element, so Promise<User> becomes User in slot 0 and so on. This is why destructuring is fully typed with no assertions — and also why passing a pre-built array typed Promise<A | B>[] loses it, collapsing to (A | B)[]. Keep the literal inline, or use as const, to keep the tuple.",
        "interviewLine": "Promise.all keeps the tuple when you pass the array literal inline. Hoist it into a variable first and the positions collapse into a union.",
        "misconception": "Expecting a union and narrowing each result. The tuple overload already resolved them positionally.",
        "hints": ["What is the difference between a tuple type and an array type here?"],
        "minutes": 3,
    },
    {
        "id": "javascript-sequential-await-serialises-work",
        "title": "Why three awaits in a row are slower than one Promise.all",
        "prompt": "The three requests are independent. What does this code cost, and why?",
        "level": "intermediate", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "async-await", "promise-all", "performance"],
        "codeSnippet": "// each request takes ~100ms\nconst a = await getA();\nconst b = await getB();\nconst c = await getC();\n// vs\nconst [x, y, z] = await Promise.all([getA(), getB(), getC()]);",
        "options": [
            ("A", "Both take about 100ms; await does not block other work", False,
             "await does not block the thread, but it does delay the next line — getB is not even started until getA resolves."),
            ("B", "The first takes about 300ms because each request starts only after the previous resolves; the second takes about 100ms", True,
             "Correct. Sequential awaits serialise independent work into a waterfall."),
            ("C", "The first is faster because it avoids the overhead of Promise.all", False,
             "The combinator overhead is negligible against three network round-trips."),
            ("D", "Both take about 300ms; Promise.all only tidies the syntax", False,
             "Promise.all starts all three immediately, so they overlap."),
        ],
        "explanation": "await suspends the function until its promise settles, so the next line — including the call that starts the next request — does not run until then. Three independent requests become a 300ms waterfall. Promise.all takes an array whose elements are already-started promises, so all three are in flight before anything is awaited and the total is roughly the slowest one. The distinction only matters when the calls are genuinely independent; if getB needs getA's id, the waterfall is the correct shape.",
        "interviewLine": "await doesn't block the thread, but it does block the next line — which is enough to turn independent calls into a waterfall.",
        "misconception": "Believing that because await is non-blocking, sequential awaits are already concurrent.",
        "hints": ["When exactly does getB() get called in the first version?"],
        "minutes": 2,
    },
    {
        "id": "javascript-promise-all-unhandled-rejection",
        "title": "Why Promise.all can leave an unhandled rejection behind",
        "prompt": "Two of the inputs reject. The catch reports the first. What about the second?",
        "level": "senior", "type": "concept", "subject": "async-await",
        "category": "javascript", "lang": "javascript",
        "tags": ["javascript", "promises", "error-handling", "unhandled-rejection"],
        "codeSnippet": "try {\n  await Promise.all([failFast(), failLater(), ok()]);\n} catch (e) {\n  report(e); // only the first rejection\n}",
        "options": [
            ("A", "It is delivered to the same catch block a moment later", False,
             "A try/catch fires once. The second rejection has nowhere to go."),
            ("B", "Promise.all attaches a handler to every input, so it is observed and silently discarded", True,
             "Correct. all subscribes to all of them, so the later rejection is handled — not reported, but not unhandled either."),
            ("C", "It always surfaces as an unhandledrejection event", False,
             "It does not: Promise.all already attached a handler to that promise."),
            ("D", "It cancels the remaining work, so the second rejection never occurs", False,
             "Nothing is cancelled and the second rejection does occur — it is just absorbed."),
        ],
        "explanation": "Promise.all subscribes to every input as it is passed in, so each has a handler attached from the start. When a second input rejects after the aggregate has already settled, that rejection is observed and dropped on the floor — no unhandledrejection event, and no way for your catch to see it. The failure is invisible rather than noisy, which is worse for diagnosis. If you need every failure, allSettled and inspect each reason. The genuine unhandled-rejection hazard is the opposite shape: creating promises first and awaiting them later, so one rejects before anything is listening.",
        "interviewLine": "all attaches handlers to every input, so later rejections are swallowed rather than reported. If you need every error, that's allSettled.",
        "misconception": "Assuming a rejection nobody reported must have triggered an unhandledrejection. Being handled and being reported are different things.",
        "hints": ["Did anything subscribe to the second promise?"],
        "minutes": 3,
    },
    {
        "id": "typescript-type-only-imports-isolated-modules",
        "title": "Why import type exists",
        "prompt": "Under isolatedModules, why must a re-exported type use export type?",
        "level": "senior", "type": "concept", "subject": "types",
        "tags": ["typescript", "import-type", "isolatedModules", "transpilation"],
        "codeSnippet": "import type { User } from \"./models\";       // erased entirely\nimport { createUser } from \"./models\";      // real import\n\nexport type { User };                        // required under isolatedModules\n// export { User };                          // error: it is a type",
        "options": [
            ("A", "A single-file transpiler cannot tell a type from a value, so the syntax has to say which it is", True,
             "Correct. Babel and SWC never build a full program, so they cannot look up whether User is a type."),
            ("B", "Types must be re-exported separately so the bundler can tree-shake them", False,
             "Types have no runtime representation to shake out."),
            ("C", "It prevents circular imports between modules", False,
             "Type-only imports do help with cycles, but that is not what the flag requires."),
            ("D", "It is a style rule enforced by ESLint rather than the compiler", False,
             "Under isolatedModules the compiler itself enforces it."),
        ],
        "explanation": "tsc knows whether an imported name is a type or a value because it type-checks the whole program. Babel, SWC and esbuild transpile one file at a time and have no such view — faced with export { User }, they cannot know whether to emit a real re-export or erase it, and emitting one for a type produces an import of something that does not exist at runtime. import type and export type make the intent explicit in the syntax. The same constraint is why const enum is disallowed: inlining its values requires cross-file type information no single-file transpiler has.",
        "interviewLine": "A single-file transpiler can't look up whether a name is a type. import type puts the answer in the syntax instead of the type checker.",
        "misconception": "Reading import type as a performance hint. It is a correctness requirement for file-at-a-time transpilers.",
        "hints": ["What does a transpiler that never sees ./models know about User?"],
        "minutes": 3,
    },
]
